import type { Question } from "../types";

const P = (en: string, ru: string) => ({ en, ru });

// Note: EN and RU analogies are authored independently (not literal
// translations) so both feel natural, while option ordering is kept
// consistent so the correct letter matches across locales.
export const verbalQuestions: Question[] = [
  {
    id: 601,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Hot is to Cold as Up is to ___", "Горячий относится к Холодный, как Верх относится к ___"),
    options: [
      { id: "A", text: P("Down", "Низ") },
      { id: "B", text: P("Sky", "Небо") },
      { id: "C", text: P("Left", "Лево") },
      { id: "D", text: P("Fast", "Быстро") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Hot and Cold are opposites; Up and Down are the equivalent pair of opposites.",
      "Горячий и Холодный — противоположности; Верх и Низ — аналогичная пара противоположностей.",
    ),
    weight: 1,
  },
  {
    id: 602,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Puppy is to Dog as Kitten is to ___", "Щенок относится к Собака, как Котёнок относится к ___"),
    options: [
      { id: "A", text: P("Cat", "Кошка") },
      { id: "B", text: P("Bird", "Птица") },
      { id: "C", text: P("Milk", "Молоко") },
      { id: "D", text: P("Paw", "Лапа") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A puppy is a baby dog, just as a kitten is a baby cat.",
      "Щенок — детёныш собаки, так же как котёнок — детёныш кошки.",
    ),
    weight: 1,
  },
  {
    id: 603,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Book is to Read as Song is to ___", "Книга относится к Читать, как Песня относится к ___"),
    options: [
      { id: "A", text: P("Listen", "Слушать") },
      { id: "B", text: P("Write", "Писать") },
      { id: "C", text: P("Paper", "Бумага") },
      { id: "D", text: P("Loud", "Громко") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A book is experienced by reading it; a song is experienced by listening to it.",
      "Книгу воспринимают через чтение; песню — через слушание.",
    ),
    weight: 1,
  },
  {
    id: 604,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Doctor is to Hospital as Teacher is to ___", "Врач относится к Больница, как Учитель относится к ___"),
    options: [
      { id: "A", text: P("School", "Школа") },
      { id: "B", text: P("Book", "Книга") },
      { id: "C", text: P("Student", "Ученик") },
      { id: "D", text: P("Pencil", "Карандаш") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A doctor's typical workplace is a hospital; a teacher's typical workplace is a school.",
      "Типичное место работы врача — больница; типичное место работы учителя — школа.",
    ),
    weight: 1.5,
  },
  {
    id: 605,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Author is to Book as Composer is to ___", "Автор относится к Книга, как Композитор относится к ___"),
    options: [
      { id: "A", text: P("Symphony", "Симфония") },
      { id: "B", text: P("Piano", "Пианино") },
      { id: "C", text: P("Orchestra", "Оркестр") },
      { id: "D", text: P("Concert", "Концерт") },
    ],
    correctAnswer: "A",
    explanation: P(
      "An author creates a book; a composer creates a symphony — both describe the creator-to-created-work relationship.",
      "Автор создаёт книгу; композитор создаёт симфонию — оба описывают отношение «создатель — созданное произведение».",
    ),
    weight: 1.5,
  },
  {
    id: 606,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Thermometer is to Temperature as Scale is to ___", "Термометр относится к Температура, как Весы относятся к ___"),
    options: [
      { id: "A", text: P("Weight", "Вес") },
      { id: "B", text: P("Time", "Время") },
      { id: "C", text: P("Distance", "Расстояние") },
      { id: "D", text: P("Speed", "Скорость") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A thermometer measures temperature; a scale measures weight — both are measuring instrument to measured quantity pairs.",
      "Термометр измеряет температуру; весы измеряют вес — обе пары описывают отношение «измерительный прибор — измеряемая величина».",
    ),
    weight: 1.5,
  },
  {
    id: 607,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Optimist is to Hopeful as Pessimist is to ___", "Оптимист относится к Полный надежд, как Пессимист относится к ___"),
    options: [
      { id: "A", text: P("Gloomy", "Мрачный") },
      { id: "B", text: P("Cheerful", "Весёлый") },
      { id: "C", text: P("Curious", "Любопытный") },
      { id: "D", text: P("Confident", "Уверенный") },
    ],
    correctAnswer: "A",
    explanation: P(
      "An optimist is characterized as hopeful; the analogous trait for a pessimist is gloomy.",
      "Оптимиста характеризует «полный надежд»; аналогичная черта пессимиста — «мрачный».",
    ),
    weight: 1.5,
  },
  {
    id: 608,
    category: "verbal",
    difficulty: "hard",
    prompt: P("Ephemeral is to Permanent as Transparent is to ___", "Эфемерный относится к Постоянный, как Прозрачный относится к ___"),
    options: [
      { id: "A", text: P("Opaque", "Непрозрачный") },
      { id: "B", text: P("Clear", "Ясный") },
      { id: "C", text: P("Fragile", "Хрупкий") },
      { id: "D", text: P("Bright", "Яркий") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Ephemeral and Permanent are antonyms; Transparent and Opaque are the corresponding antonym pair.",
      "Эфемерный и Постоянный — антонимы; Прозрачный и Непрозрачный — соответствующая пара антонимов.",
    ),
    weight: 2,
  },
  {
    id: 609,
    category: "verbal",
    difficulty: "hard",
    prompt: P("Frugal is to Miserly as Confident is to ___", "Бережливый относится к Скупой, как Уверенный относится к ___"),
    options: [
      { id: "A", text: P("Arrogant", "Высокомерный") },
      { id: "B", text: P("Shy", "Застенчивый") },
      { id: "C", text: P("Kind", "Добрый") },
      { id: "D", text: P("Honest", "Честный") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Miserly is an extreme, negative degree of frugal; arrogant is the analogous extreme, negative degree of confident.",
      "Скупой — это крайняя, негативная степень бережливости; высокомерный — аналогичная крайняя, негативная степень уверенности.",
    ),
    weight: 2,
  },
  {
    id: 610,
    category: "verbal",
    difficulty: "hard",
    prompt: P("Seed is to Tree as Egg is to ___", "Семя относится к Дерево, как Яйцо относится к ___"),
    options: [
      { id: "A", text: P("Bird", "Птица") },
      { id: "B", text: P("Nest", "Гнездо") },
      { id: "C", text: P("Shell", "Скорлупа") },
      { id: "D", text: P("Farm", "Ферма") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A seed develops into a tree; an egg develops into a bird — both describe an early stage developing into its mature form.",
      "Семя развивается в дерево; яйцо развивается в птицу — обе пары описывают развитие ранней стадии в зрелую форму.",
    ),
    weight: 2,
  },
  {
    id: 611,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Key is to Lock as Password is to ___", "Ключ относится к Замок, как Пароль относится к ___"),
    options: [
      { id: "A", text: P("Account", "Аккаунт") },
      { id: "B", text: P("Computer", "Компьютер") },
      { id: "C", text: P("Letter", "Буква") },
      { id: "D", text: P("Internet", "Интернет") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A key grants access to a lock; a password grants access to an account.",
      "Ключ открывает доступ к замку; пароль открывает доступ к аккаунту.",
    ),
    weight: 1.5,
  },
  {
    id: 612,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Fish is to Water as Bird is to ___", "Рыба относится к Вода, как Птица относится к ___"),
    options: [
      { id: "A", text: P("Air", "Воздух") },
      { id: "B", text: P("Nest", "Гнездо") },
      { id: "C", text: P("Tree", "Дерево") },
      { id: "D", text: P("Feather", "Перо") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A fish's natural habitat is water; a bird's natural habitat/medium of movement is air.",
      "Естественная среда обитания рыбы — вода; естественная среда передвижения птицы — воздух.",
    ),
    weight: 1,
  },
  {
    id: 613,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Baker is to Bread as Tailor is to ___", "Пекарь относится к Хлеб, как Портной относится к ___"),
    options: [
      { id: "A", text: P("Clothes", "Одежда") },
      { id: "B", text: P("Needle", "Иголка") },
      { id: "C", text: P("Shop", "Магазин") },
      { id: "D", text: P("Thread", "Нить") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A baker produces bread; a tailor produces clothes — both describe a maker and their typical product.",
      "Пекарь производит хлеб; портной производит одежду — обе пары описывают отношение «мастер — типичное изделие».",
    ),
    weight: 1,
  },
  {
    id: 614,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Pen is to Write as Scissors is to ___", "Ручка относится к Писать, как Ножницы относятся к ___"),
    options: [
      { id: "A", text: P("Cut", "Резать") },
      { id: "B", text: P("Paper", "Бумага") },
      { id: "C", text: P("Sharp", "Острый") },
      { id: "D", text: P("Metal", "Металл") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A pen's function is to write; scissors' function is to cut — both pair a tool with its primary action.",
      "Функция ручки — писать; функция ножниц — резать. Обе пары связывают инструмент с его основным действием.",
    ),
    weight: 1,
  },
  {
    id: 615,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Calf is to Cow as Foal is to ___", "Телёнок относится к Корова, как Жеребёнок относится к ___"),
    options: [
      { id: "A", text: P("Horse", "Лошадь") },
      { id: "B", text: P("Sheep", "Овца") },
      { id: "C", text: P("Barn", "Сарай") },
      { id: "D", text: P("Saddle", "Седло") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A calf is a baby cow, just as a foal is a baby horse.",
      "Телёнок — детёныш коровы, так же как жеребёнок — детёныш лошади.",
    ),
    weight: 1,
  },
  {
    id: 616,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Sculptor is to Chisel as Painter is to ___", "Скульптор относится к Резец, как Художник относится к ___"),
    options: [
      { id: "A", text: P("Brush", "Кисть") },
      { id: "B", text: P("Canvas", "Холст") },
      { id: "C", text: P("Gallery", "Галерея") },
      { id: "D", text: P("Frame", "Рама") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A sculptor's primary tool is a chisel; a painter's primary tool is a brush — both are craftsman-to-primary-tool pairs.",
      "Основной инструмент скульптора — резец; основной инструмент художника — кисть. Обе пары описывают отношение «мастер — основной инструмент».",
    ),
    weight: 1.5,
  },
  {
    id: 617,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Judge is to Courtroom as Surgeon is to ___", "Судья относится к Зал суда, как Хирург относится к ___"),
    options: [
      { id: "A", text: P("Operating room", "Операционная") },
      { id: "B", text: P("Scalpel", "Скальпель") },
      { id: "C", text: P("Patient", "Пациент") },
      { id: "D", text: P("Hospital gown", "Больничный халат") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A judge's typical workplace is the courtroom; a surgeon's typical workplace is the operating room.",
      "Типичное рабочее место судьи — зал суда; типичное рабочее место хирурга — операционная.",
    ),
    weight: 1.5,
  },
  {
    id: 618,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Generous is to Stingy as Brave is to ___", "Щедрый относится к Скупой, как Смелый относится к ___"),
    options: [
      { id: "A", text: P("Cowardly", "Трусливый") },
      { id: "B", text: P("Bold", "Отважный") },
      { id: "C", text: P("Loyal", "Верный") },
      { id: "D", text: P("Wise", "Мудрый") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Generous and Stingy are antonyms; Brave and Cowardly are the corresponding antonym pair.",
      "Щедрый и Скупой — антонимы; Смелый и Трусливый — соответствующая пара антонимов.",
    ),
    weight: 1.5,
  },
  {
    id: 619,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Compass is to Direction as Clock is to ___", "Компас относится к Направление, как Часы относятся к ___"),
    options: [
      { id: "A", text: P("Time", "Время") },
      { id: "B", text: P("Metal", "Металл") },
      { id: "C", text: P("Wall", "Стена") },
      { id: "D", text: P("Battery", "Батарейка") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A compass measures/indicates direction; a clock measures/indicates time — an instrument-to-measured-quantity pair.",
      "Компас измеряет и указывает направление; часы измеряют и показывают время — отношение «прибор — измеряемая величина».",
    ),
    weight: 1.5,
  },
  {
    id: 620,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Chapter is to Book as Scene is to ___", "Глава относится к Книга, как Сцена относится к ___"),
    options: [
      { id: "A", text: P("Play", "Пьеса") },
      { id: "B", text: P("Actor", "Актёр") },
      { id: "C", text: P("Stage", "Сцена (помост)") },
      { id: "D", text: P("Curtain", "Занавес") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A chapter is a structural part of a book; a scene is the analogous structural part of a play.",
      "Глава — структурная часть книги; сцена — аналогичная структурная часть пьесы.",
    ),
    weight: 1.5,
  },
  {
    id: 621,
    category: "verbal",
    difficulty: "hard",
    prompt: P("Meticulous is to Careless as Eloquent is to ___", "Дотошный относится к Небрежный, как Красноречивый относится к ___"),
    options: [
      { id: "A", text: P("Inarticulate", "Невнятный") },
      { id: "B", text: P("Persuasive", "Убедительный") },
      { id: "C", text: P("Talkative", "Разговорчивый") },
      { id: "D", text: P("Quiet", "Тихий") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Meticulous and Careless are antonyms; Eloquent and Inarticulate form the corresponding antonym pair.",
      "Дотошный и Небрежный — антонимы; Красноречивый и Невнятный — соответствующая пара антонимов.",
    ),
    weight: 2,
  },
  {
    id: 622,
    category: "verbal",
    difficulty: "hard",
    prompt: P("Reckless is to Careful as Naive is to ___", "Безрассудный относится к Осторожный, как Наивный относится к ___"),
    options: [
      { id: "A", text: P("Shrewd", "Проницательный") },
      { id: "B", text: P("Young", "Молодой") },
      { id: "C", text: P("Kind", "Добрый") },
      { id: "D", text: P("Trusting", "Доверчивый") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Reckless and Careful are opposites; Naive and Shrewd form the corresponding pair of opposites (unworldly vs. sharply perceptive).",
      "Безрассудный и Осторожный — противоположности; Наивный и Проницательный — соответствующая пара противоположностей.",
    ),
    weight: 2,
  },
  {
    id: 623,
    category: "verbal",
    difficulty: "hard",
    prompt: P("Caterpillar is to Butterfly as Tadpole is to ___", "Гусеница относится к Бабочка, как Головастик относится к ___"),
    options: [
      { id: "A", text: P("Frog", "Лягушка") },
      { id: "B", text: P("Pond", "Пруд") },
      { id: "C", text: P("Fish", "Рыба") },
      { id: "D", text: P("Egg", "Яйцо") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A caterpillar metamorphoses into a butterfly; a tadpole metamorphoses into a frog — both describe a larval stage becoming its adult form.",
      "Гусеница превращается в бабочку; головастик превращается в лягушку — обе пары описывают превращение личиночной стадии во взрослую форму.",
    ),
    weight: 2,
  },
  {
    id: 624,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Umbrella is to Rain as Sunscreen is to ___", "Зонт относится к Дождь, как Солнцезащитный крем относится к ___"),
    options: [
      { id: "A", text: P("Sunburn", "Солнечный ожог") },
      { id: "B", text: P("Beach", "Пляж") },
      { id: "C", text: P("Summer", "Лето") },
      { id: "D", text: P("Skin", "Кожа") },
    ],
    correctAnswer: "A",
    explanation: P(
      "An umbrella protects against rain; sunscreen protects against sunburn — both pair a protective item with what it guards against.",
      "Зонт защищает от дождя; крем защищает от солнечного ожога — обе пары связывают защитное средство с тем, от чего оно защищает.",
    ),
    weight: 1.5,
  },
  {
    id: 625,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Sugar is to Sweet as Lemon is to ___", "Сахар относится к Сладкий, как Лимон относится к ___"),
    options: [
      { id: "A", text: P("Sour", "Кислый") },
      { id: "B", text: P("Yellow", "Жёлтый") },
      { id: "C", text: P("Juice", "Сок") },
      { id: "D", text: P("Fruit", "Фрукт") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Sugar's defining taste is sweet; a lemon's defining taste is sour.",
      "Отличительный вкус сахара — сладкий; отличительный вкус лимона — кислый.",
    ),
    weight: 1,
  },
  {
    id: 626,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Conductor is to Orchestra as Captain is to ___", "Дирижёр относится к Оркестр, как Капитан относится к ___"),
    options: [
      { id: "A", text: P("Team", "Команда") },
      { id: "B", text: P("Ship", "Корабль") },
      { id: "C", text: P("Uniform", "Форма") },
      { id: "D", text: P("Whistle", "Свисток") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A conductor leads an orchestra; a captain leads a team — both describe a leader-to-led-group relationship.",
      "Дирижёр руководит оркестром; капитан руководит командой — обе пары описывают отношение «руководитель — руководимая группа».",
    ),
    weight: 1.5,
  },
  {
    id: 627,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Blueprint is to Building as Recipe is to ___", "Чертёж относится к Здание, как Рецепт относится к ___"),
    options: [
      { id: "A", text: P("Dish", "Блюдо") },
      { id: "B", text: P("Kitchen", "Кухня") },
      { id: "C", text: P("Chef", "Повар") },
      { id: "D", text: P("Ingredients", "Ингредиенты") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A blueprint is the plan followed to construct a building; a recipe is the plan followed to prepare a dish.",
      "Чертёж — это план, по которому строят здание; рецепт — план, по которому готовят блюдо.",
    ),
    weight: 1.5,
  },
  {
    id: 628,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Library is to Books as Museum is to ___", "Библиотека относится к Книги, как Музей относится к ___"),
    options: [
      { id: "A", text: P("Exhibits", "Экспонаты") },
      { id: "B", text: P("Tickets", "Билеты") },
      { id: "C", text: P("Guide", "Экскурсовод") },
      { id: "D", text: P("Building", "Здание") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A library houses and lends books; a museum houses and displays exhibits — both pair an institution with what it holds.",
      "Библиотека хранит и выдаёт книги; музей хранит и показывает экспонаты — обе пары связывают учреждение с тем, что оно содержит.",
    ),
    weight: 1,
  },
  {
    id: 629,
    category: "verbal",
    difficulty: "hard",
    prompt: P("Verbose is to Concise as Opaque is to ___", "Многословный относится к Лаконичный, как Непрозрачный относится к ___"),
    options: [
      { id: "A", text: P("Transparent", "Прозрачный") },
      { id: "B", text: P("Dark", "Тёмный") },
      { id: "C", text: P("Thick", "Плотный") },
      { id: "D", text: P("Colorful", "Красочный") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Verbose and Concise are antonyms describing excess versus economy of language; Opaque and Transparent form the analogous antonym pair for how easily light or meaning passes through.",
      "Многословный и Лаконичный — антонимы, описывающие избыток и экономию слов; Непрозрачный и Прозрачный — аналогичная пара антонимов для того, как легко проходит свет или смысл.",
    ),
    weight: 2,
  },
  {
    id: 630,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Nurse is to Clinic as Pilot is to ___", "Медсестра относится к Поликлиника, как Пилот относится к ___"),
    options: [
      { id: "A", text: P("Cockpit", "Кабина пилота") },
      { id: "B", text: P("Airport", "Аэропорт") },
      { id: "C", text: P("Runway", "Взлётная полоса") },
      { id: "D", text: P("Sky", "Небо") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A nurse's immediate workplace within a larger facility is the clinic room; a pilot's immediate workplace within the aircraft is the cockpit.",
      "Непосредственное рабочее место медсестры внутри учреждения — кабинет; непосредственное рабочее место пилота внутри самолёта — кабина пилота.",
    ),
    weight: 1.5,
  },
  {
    id: 631,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Wolf is to Pack as Bee is to ___", "Волк относится к Стая, как Пчела относится к ___"),
    options: [
      { id: "A", text: P("Hive", "Улей") },
      { id: "B", text: P("Honey", "Мёд") },
      { id: "C", text: P("Flower", "Цветок") },
      { id: "D", text: P("Sting", "Жало") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A wolf lives and operates within a pack; a bee lives and operates within a hive — a social-animal-to-group pairing.",
      "Волк живёт и действует в составе стаи; пчела живёт и действует в составе улья (роя) — пара «социальное животное — группа».",
    ),
    weight: 1,
  },
  {
    id: 632,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Diploma is to Graduation as Trophy is to ___", "Диплом относится к Выпуск, как Кубок относится к ___"),
    options: [
      { id: "A", text: P("Victory", "Победа") },
      { id: "B", text: P("Sport", "Спорт") },
      { id: "C", text: P("Shelf", "Полка") },
      { id: "D", text: P("Team", "Команда") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A diploma is awarded for graduation; a trophy is awarded for victory — both are award-to-achievement pairs.",
      "Диплом вручают за выпуск; кубок вручают за победу — обе пары описывают отношение «награда — достижение».",
    ),
    weight: 1.5,
  },
  {
    id: 633,
    category: "verbal",
    difficulty: "hard",
    prompt: P("Wither is to Bloom as Decline is to ___", "Увядать относится к Расцветать, как Приходить в упадок относится к ___"),
    options: [
      { id: "A", text: P("Flourish", "Процветать") },
      { id: "B", text: P("Fall", "Падать") },
      { id: "C", text: P("Grow old", "Стареть") },
      { id: "D", text: P("Rest", "Отдыхать") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Wither and Bloom are opposites (fading versus thriving); Decline and Flourish form the corresponding opposite pair.",
      "Увядать и Расцветать — противоположности (угасание против процветания); Приходить в упадок и Процветать — соответствующая пара противоположностей.",
    ),
    weight: 2,
  },
  {
    id: 634,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Thief is to Steal as Liar is to ___", "Вор относится к Воровать, как Лжец относится к ___"),
    options: [
      { id: "A", text: P("Deceive", "Обманывать") },
      { id: "B", text: P("Speak", "Говорить") },
      { id: "C", text: P("Hide", "Прятаться") },
      { id: "D", text: P("Whisper", "Шептать") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A thief's defining action is to steal; a liar's defining action is to deceive — a person-to-characteristic-action pair.",
      "Определяющее действие вора — воровать; определяющее действие лжеца — обманывать. Пара «человек — характерное действие».",
    ),
    weight: 1.5,
  },
  {
    id: 635,
    category: "verbal",
    difficulty: "easy",
    prompt: P("Winter is to Cold as Summer is to ___", "Зима относится к Холодная, как Лето относится к ___"),
    options: [
      { id: "A", text: P("Hot", "Жаркое") },
      { id: "B", text: P("Rainy", "Дождливое") },
      { id: "C", text: P("Short", "Короткое") },
      { id: "D", text: P("Windy", "Ветреное") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Winter's defining trait is being cold; summer's defining trait is being hot — a season-to-typical-quality pair.",
      "Определяющая черта зимы — холод; определяющая черта лета — жара. Пара «сезон — типичное качество».",
    ),
    weight: 1,
  },
  {
    id: 636,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Anchor is to Ship as Root is to ___", "Якорь относится к Корабль, как Корень относится к ___"),
    options: [
      { id: "A", text: P("Tree", "Дерево") },
      { id: "B", text: P("Soil", "Почва") },
      { id: "C", text: P("Leaf", "Лист") },
      { id: "D", text: P("Flower", "Цветок") },
    ],
    correctAnswer: "A",
    explanation: P(
      "An anchor holds a ship firmly in place; a root holds a tree firmly in place — both describe a structure that anchors something to keep it stable.",
      "Якорь удерживает корабль на месте; корень удерживает дерево на месте — обе пары описывают элемент, обеспечивающий устойчивость.",
    ),
    weight: 1.5,
  },
  {
    id: 637,
    category: "verbal",
    difficulty: "hard",
    prompt: P("Skeptic is to Doubtful as Zealot is to ___", "Скептик относится к Сомневающийся, как Фанатик относится к ___"),
    options: [
      { id: "A", text: P("Fervent", "Ревностный") },
      { id: "B", text: P("Calm", "Спокойный") },
      { id: "C", text: P("Curious", "Любопытный") },
      { id: "D", text: P("Lazy", "Ленивый") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A skeptic is characterized as doubtful; the analogous defining trait of a zealot is fervent (intensely devoted/passionate).",
      "Скептика характеризует сомнение; аналогичная определяющая черта фанатика — ревностность (сильная преданность и страсть).",
    ),
    weight: 2,
  },
  {
    id: 638,
    category: "verbal",
    difficulty: "medium",
    prompt: P("Vaccine is to Prevent as Antidote is to ___", "Вакцина относится к Предотвращать, как Противоядие относится к ___"),
    options: [
      { id: "A", text: P("Counteract", "Обезвреживать") },
      { id: "B", text: P("Cause", "Вызывать") },
      { id: "C", text: P("Diagnose", "Диагностировать") },
      { id: "D", text: P("Ignore", "Игнорировать") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A vaccine's function is to prevent disease before it happens; an antidote's function is to counteract poison after exposure — both are substance-to-primary-function pairs.",
      "Функция вакцины — предотвращать болезнь до её появления; функция противоядия — обезвреживать яд после воздействия. Обе пары описывают отношение «вещество — основная функция».",
    ),
    weight: 1.5,
  },
];
