import type { Question, VisualSpec } from "../types";

const P = (en: string, ru: string) => ({ en, ru });

function arrow(steps: (number | "blank")[]): VisualSpec {
  return { kind: "arrowRotation", steps };
}
function custom(id: string): VisualSpec {
  return { kind: "custom", id };
}

export const spatialQuestions: Question[] = [
  {
    id: 401,
    category: "spatial",
    difficulty: "easy",
    prompt: P(
      "The arrow rotates by a fixed angle clockwise each step. What is its next direction?",
      "Стрелка поворачивается на фиксированный угол по часовой стрелке на каждом шаге. Куда она укажет далее?",
    ),
    visual: arrow([0, 90, 180, 270, "blank"]),
    options: [
      { id: "A", text: P("Pointing up", "Вверх") },
      { id: "B", text: P("Pointing right", "Вправо") },
      { id: "C", text: P("Pointing down", "Вниз") },
      { id: "D", text: P("Pointing left", "Влево") },
    ],
    correctAnswer: "B",
    explanation: P(
      "The arrow rotates 90° clockwise each step, cycling right→down→left→up→right. After up (270°) comes right (360° = 0°).",
      "Стрелка поворачивается на 90° по часовой стрелке: вправо→вниз→влево→вверх→вправо. После положения «вверх» (270°) снова «вправо» (360° = 0°).",
    ),
    weight: 1,
  },
  {
    id: 402,
    category: "spatial",
    difficulty: "easy",
    prompt: P(
      "The arrow rotates 45° clockwise each step. What is the next direction after four steps shown?",
      "Стрелка поворачивается на 45° по часовой стрелке на каждом шаге. Каково направление после четырёх показанных шагов?",
    ),
    visual: arrow([0, 45, 90, 135, "blank"]),
    options: [
      { id: "A", text: P("Straight left (180°)", "Прямо влево (180°)") },
      { id: "B", text: P("Straight down (270°)", "Прямо вниз (270°)") },
      { id: "C", text: P("Up-right diagonal (315°)", "По диагонали вверх-вправо (315°)") },
      { id: "D", text: P("Down-right diagonal (225°)", "По диагонали вниз-вправо (225°)") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Each step adds 45° clockwise starting from 0° (pointing right): 0°, 45°, 90°, 135°, 180°. At 180° the arrow points straight left.",
      "Каждый шаг добавляет 45° по часовой стрелке, начиная с 0° (стрелка вправо): 0°, 45°, 90°, 135°, 180°. При 180° стрелка направлена прямо влево.",
    ),
    weight: 1,
  },
  {
    id: 403,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "The arrow alternates between rotating 90° and 45° clockwise each step (90, 45, 90, 45...). Starting at 0°, what is the direction after 4 steps?",
      "Стрелка чередует повороты на 90° и 45° по часовой стрелке (90, 45, 90, 45...). Начиная с 0°, каково направление после 4 шагов?",
    ),
    options: [
      { id: "A", text: P("225°", "225°") },
      { id: "B", text: P("270°", "270°") },
      { id: "C", text: P("180°", "180°") },
      { id: "D", text: P("315°", "315°") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Cumulative rotation: 0 → +90=90 → +45=135 → +90=225. After 4 steps (3 rotations applied) the angle is 225°.",
      "Суммарный поворот: 0 → +90=90 → +45=135 → +90=225. После 4 шагов (3 поворота) угол равен 225°.",
    ),
    weight: 1.5,
  },
  {
    id: 404,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "If you fold this flat cross-shaped pattern into a cube, which pair of faces will end up opposite each other?",
      "Если сложить эту плоскую фигуру-крест в куб, какая пара граней окажется противоположной?",
    ),
    visual: custom("cubeNetCross"),
    options: [
      { id: "A", text: P("1 and 6", "1 и 6") },
      { id: "B", text: P("2 and 4", "2 и 4") },
      { id: "C", text: P("3 and 5", "3 и 5") },
      { id: "D", text: P("1 and 3", "1 и 3") },
    ],
    correctAnswer: "A",
    explanation: P(
      "In a standard cross-shaped cube net with faces numbered 1–6 (1 at the top of the vertical arm, 6 at the bottom), the top and bottom faces of the arm end up directly opposite each other once folded: faces 1 and 6.",
      "В стандартной развёртке куба в виде креста с гранями, пронумерованными 1–6 (1 сверху вертикальной полосы, 6 снизу), верхняя и нижняя грани после складывания оказываются друг напротив друга: грани 1 и 6.",
    ),
    weight: 1.5,
  },
  {
    id: 405,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "A square sheet of paper is folded in half twice (into a smaller square) and a hole is punched through all layers near the folded corner. How many holes will there be when unfolded?",
      "Квадратный лист бумаги складывают пополам дважды (в меньший квадрат) и пробивают отверстие через все слои у сложенного угла. Сколько отверстий будет при разворачивании?",
    ),
    visual: custom("paperFold2x"),
    options: [
      { id: "A", text: P("2", "2") },
      { id: "B", text: P("3", "3") },
      { id: "C", text: P("4", "4") },
      { id: "D", text: P("8", "8") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Two folds create 4 layers of paper (2²=4). A single punch through all layers produces 4 holes when unfolded, arranged symmetrically around the folded corner.",
      "Два сгиба создают 4 слоя бумаги (2²=4). Один прокол через все слои даёт 4 отверстия при разворачивании, расположенных симметрично относительно сложенного угла.",
    ),
    weight: 1.5,
  },
  {
    id: 406,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "A cube has faces marked 1 through 6 (opposite faces sum to 7, as on a standard die). If face 2 is facing you and face 3 is on top, which face is on the right side?",
      "На кубе грани отмечены от 1 до 6 (противоположные грани в сумме дают 7, как на стандартном кубике). Если грань 2 обращена к вам, а грань 3 сверху, какая грань справа?",
    ),
    visual: custom("standardDie"),
    options: [
      { id: "A", text: P("1", "1") },
      { id: "B", text: P("4", "4") },
      { id: "C", text: P("5", "5") },
      { id: "D", text: P("6", "6") },
    ],
    correctAnswer: "C",
    explanation: P(
      "With 2 facing you and 3 on top, using the standard die arrangement (1-2-3 run counter-clockwise around their shared corner), the face to the right is 5.",
      "Если 2 обращена к вам, а 3 сверху, то по стандартному расположению граней кубика (1-2-3 идут против часовой стрелки вокруг общей вершины) справа окажется грань 5.",
    ),
    weight: 2,
  },
  {
    id: 407,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "Looking at an uppercase letter 'F' printed on glass from the front, what does it look like from the back of the glass (mirrored)?",
      "Если смотреть на заглавную букву «F», напечатанную на стекле, спереди, как она будет выглядеть с обратной стороны стекла (зеркально)?",
    ),
    visual: custom("mirrorF"),
    options: [
      { id: "A", text: P("A backwards F (mirror image)", "Зеркально отражённая F") },
      { id: "B", text: P("An upside-down F", "Перевёрнутая вверх ногами F") },
      { id: "C", text: P("The same F", "Такая же F") },
      { id: "D", text: P("An upside-down and backwards F", "Перевёрнутая и зеркально отражённая F") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Viewing text through the back of glass flips it left-to-right (a mirror reflection), but does not flip it vertically. The result is a backwards F.",
      "При взгляде на текст с обратной стороны стекла он отражается слева направо (зеркально), но не переворачивается по вертикали. Результат — зеркально отражённая F.",
    ),
    weight: 2,
  },
  {
    id: 408,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "An L-shaped tile is rotated 90° clockwise each step. What is its orientation after 3 rotations from the starting position shown?",
      "L-образная плитка поворачивается на 90° по часовой стрелке на каждом шаге. Каково её положение после 3 поворотов от исходного, показанного положения?",
    ),
    visual: custom("lShapeRotation"),
    options: [
      { id: "A", text: P("Rotated 270° from start", "Повёрнута на 270° от начального положения") },
      { id: "B", text: P("Rotated 90° from start", "Повёрнута на 90° от начального положения") },
      { id: "C", text: P("Same as start", "Как в начале") },
      { id: "D", text: P("Mirrored, not rotated", "Отражена, но не повёрнута") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Three rotations of 90° each accumulate to 270° clockwise from the starting orientation.",
      "Три поворота по 90° в сумме дают 270° по часовой стрелке от начального положения.",
    ),
    weight: 1.5,
  },
  {
    id: 409,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "Which of the following 2D nets, when folded, forms a closed triangular pyramid (tetrahedron) with no gaps or overlaps?",
      "Какая из следующих плоских разверток при складывании образует закрытую треугольную пирамиду (тетраэдр) без зазоров и наложений?",
    ),
    visual: custom("tetrahedronNet"),
    options: [
      { id: "A", text: P("A large triangle divided into 4 smaller equal triangles", "Большой треугольник, разделённый на 4 меньших равных треугольника") },
      { id: "B", text: P("A square with 4 triangles attached to its sides", "Квадрат с 4 треугольниками по сторонам") },
      { id: "C", text: P("Six squares arranged in a cross", "Шесть квадратов, расположенных крестом") },
      { id: "D", text: P("Three squares in a row", "Три квадрата в ряд") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A tetrahedron has 4 triangular faces. A large triangle split into 4 equal smaller triangles folds along the internal lines into a closed tetrahedron. The other nets fold into a pyramid with a square base, a cube pattern, or nothing closed.",
      "Тетраэдр имеет 4 треугольные грани. Большой треугольник, разделённый на 4 равных треугольника, складывается по внутренним линиям в закрытый тетраэдр. Остальные развёртки дают пирамиду с квадратным основанием, куб или не складываются в закрытую фигуру.",
    ),
    weight: 1.5,
  },
  {
    id: 410,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "A shape is rotated 90° clockwise, then reflected horizontally, then rotated 180°. Starting from an arrow pointing up, in which direction does it now point?",
      "Фигуру поворачивают на 90° по часовой стрелке, затем отражают по горизонтали, затем поворачивают на 180°. Если исходно стрелка указывала вверх, куда она указывает теперь?",
    ),
    options: [
      { id: "A", text: P("Left", "Влево") },
      { id: "B", text: P("Right", "Вправо") },
      { id: "C", text: P("Up", "Вверх") },
      { id: "D", text: P("Down", "Вниз") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Up → rotate 90° CW → right. Reflect horizontally (flip left-right) → an arrow pointing right stays pointing right (horizontal flip doesn't affect a horizontal direction... but reflection flips left/right pointing arrows) — right becomes left. Rotate 180° → left becomes right. Final direction: right.",
      "Вверх → поворот на 90° по часовой стрелке → вправо. Отражение по горизонтали (влево-вправо) превращает «вправо» в «влево». Поворот на 180° возвращает «влево» обратно в «вправо». Итоговое направление: вправо.",
    ),
    weight: 2,
  },
  {
    id: 411,
    category: "spatial",
    difficulty: "easy",
    prompt: P(
      "The arrow rotates 90° counter-clockwise each step. What is the next direction?",
      "Стрелка поворачивается на 90° против часовой стрелки на каждом шаге. Каково следующее направление?",
    ),
    visual: arrow([0, 270, 180, 90, "blank"]),
    options: [
      { id: "A", text: P("Pointing right (0°)", "Вправо (0°)") },
      { id: "B", text: P("Pointing down (270°)", "Вниз (270°)") },
      { id: "C", text: P("Pointing left (180°)", "Влево (180°)") },
      { id: "D", text: P("Pointing up (90°)", "Вверх (90°)") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Rotating 90° counter-clockwise each step cycles right→up→left→down→right. After 90° (up) comes back to 0° (right).",
      "Поворот на 90° против часовой стрелки: вправо→вверх→влево→вниз→вправо. После положения «вверх» (90°) снова «вправо» (0°).",
    ),
    weight: 1,
  },
  {
    id: 412,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "You view a 3×3×3 cube made of 27 small cubes. All outer faces are painted red. If the whole cube is disassembled, how many small cubes have exactly 2 red faces?",
      "Вы рассматриваете куб 3×3×3, состоящий из 27 маленьких кубиков. Все внешние грани окрашены в красный. Если куб разобрать, сколько маленьких кубиков будут иметь ровно 2 красные грани?",
    ),
    options: [
      { id: "A", text: P("8", "8") },
      { id: "B", text: P("12", "12") },
      { id: "C", text: P("6", "6") },
      { id: "D", text: P("1", "1") },
    ],
    correctAnswer: "B",
    explanation: P(
      "In a 3×3×3 painted cube: 8 corner cubes have 3 painted faces, 12 edge cubes have exactly 2 painted faces, 6 face-center cubes have 1 painted face, and 1 center cube has none.",
      "В окрашенном кубе 3×3×3: 8 угловых кубиков имеют 3 окрашенные грани, 12 рёберных кубиков — ровно 2 окрашенные грани, 6 кубиков в центре граней — 1 окрашенную грань, а 1 центральный — ни одной.",
    ),
    weight: 2,
  },
  {
    id: 413,
    category: "spatial",
    difficulty: "easy",
    prompt: P(
      "The arrow rotates 135° clockwise each step. What is the next direction?",
      "Стрелка поворачивается на 135° по часовой стрелке на каждом шаге. Каково следующее направление?",
    ),
    visual: arrow([0, 135, 270, "blank"]),
    options: [
      { id: "A", text: P("45°", "45°") },
      { id: "B", text: P("225°", "225°") },
      { id: "C", text: P("90°", "90°") },
      { id: "D", text: P("315°", "315°") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Each step adds 135°: 0°, 135°, 270°, 405°. 405° − 360° = 45°.",
      "Каждый шаг добавляет 135°: 0°, 135°, 270°, 405°. 405° − 360° = 45°.",
    ),
    weight: 1,
  },
  {
    id: 414,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "The arrow rotates 30° counter-clockwise each step. Starting at 0° (right), what direction is it after 5 steps?",
      "Стрелка поворачивается на 30° против часовой стрелки на каждом шаге. Начиная с 0° (вправо), каково направление после 5 шагов?",
    ),
    options: [
      { id: "A", text: P("150°", "150°") },
      { id: "B", text: P("180°", "180°") },
      { id: "C", text: P("120°", "120°") },
      { id: "D", text: P("210°", "210°") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Counter-clockwise rotation of 30° per step, over 5 steps, totals 150° counter-clockwise from 0°, i.e. 150°.",
      "Поворот на 30° против часовой стрелки за 5 шагов даёт в сумме 150° от 0°, то есть 150°.",
    ),
    weight: 1.5,
  },
  {
    id: 415,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "A cube has faces marked 1 through 6 (opposite faces sum to 7). If face 1 is facing you and face 2 is on top, which face is on the bottom?",
      "На кубе грани отмечены от 1 до 6 (противоположные грани в сумме дают 7). Если грань 1 обращена к вам, а грань 2 сверху, какая грань снизу?",
    ),
    visual: custom("standardDie"),
    options: [
      { id: "A", text: P("5", "5") },
      { id: "B", text: P("6", "6") },
      { id: "C", text: P("4", "4") },
      { id: "D", text: P("3", "3") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Opposite faces sum to 7. Face 2 is on top, so the bottom face is 7 − 2 = 5.",
      "Противоположные грани в сумме дают 7. Грань 2 сверху, значит снизу грань 7 − 2 = 5.",
    ),
    weight: 1.5,
  },
  {
    id: 416,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "A cube has faces marked 1 through 6 (opposite faces sum to 7). If face 4 is facing you and face 6 is on top, which face is on the left side?",
      "На кубе грани отмечены от 1 до 6 (противоположные грани в сумме дают 7). Если грань 4 обращена к вам, а грань 6 сверху, какая грань слева?",
    ),
    visual: custom("standardDie"),
    options: [
      { id: "A", text: P("2", "2") },
      { id: "B", text: P("5", "5") },
      { id: "C", text: P("1", "1") },
      { id: "D", text: P("3", "3") },
    ],
    correctAnswer: "A",
    explanation: P(
      "With 4 facing you and 6 on top, the remaining faces (1, 2, 3, 5) wrap around the sides. Using the standard die arrangement where 1-2-3 run counter-clockwise around their shared corner, the left face works out to 2.",
      "Если 4 обращена к вам, а 6 сверху, оставшиеся грани (1, 2, 3, 5) располагаются по бокам. По стандартному расположению граней кубика (1-2-3 идут против часовой стрелки вокруг общей вершины) слева оказывается грань 2.",
    ),
    weight: 2,
  },
  {
    id: 417,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "A square sheet of paper is folded in half three times (into a smaller shape) and a hole is punched through all layers near the center of the folded edge. How many holes appear when unfolded?",
      "Квадратный лист бумаги складывают пополам трижды и пробивают отверстие через все слои у центра сложенного края. Сколько отверстий появится при разворачивании?",
    ),
    visual: custom("paperFold2x"),
    options: [
      { id: "A", text: P("8", "8") },
      { id: "B", text: P("6", "6") },
      { id: "C", text: P("4", "4") },
      { id: "D", text: P("16", "16") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Three folds create 2³ = 8 layers of paper. A single punch through all layers produces 8 holes when unfolded.",
      "Три сгиба создают 2³ = 8 слоёв бумаги. Один прокол через все слои даёт 8 отверстий при разворачивании.",
    ),
    weight: 1.5,
  },
  {
    id: 418,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "Looking at the word 'BOX' printed on a glass door from the front, how does it read from the back of the door?",
      "Если смотреть на слово «BOX», напечатанное на стеклянной двери, спереди, как оно читается с обратной стороны двери?",
    ),
    visual: custom("mirrorF"),
    options: [
      { id: "A", text: P("As a mirror-image of BOX (reversed letter order and shapes)", "Как зеркальное отражение BOX (обратный порядок и форма букв)") },
      { id: "B", text: P("As BOX, unchanged", "Как BOX, без изменений") },
      { id: "C", text: P("As XOB, but each letter unmirrored", "Как XOB, но каждая буква не отражена") },
      { id: "D", text: P("As an upside-down BOX", "Как перевёрнутое вверх ногами BOX") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Viewing text through glass from the back mirrors it left-to-right entirely: both the letter order reverses and each individual letter's shape mirrors, producing a true mirror-image, not just a simple reordering.",
      "При взгляде на текст через стекло с обратной стороны он полностью зеркально отражается по горизонтали: меняется и порядок букв, и форма каждой буквы — получается настоящее зеркальное отражение, а не просто изменение порядка.",
    ),
    weight: 2,
  },
  {
    id: 419,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "An L-shaped tile is rotated 90° clockwise each step. What is its orientation after 6 rotations from the starting position shown?",
      "L-образная плитка поворачивается на 90° по часовой стрелке на каждом шаге. Каково её положение после 6 поворотов от исходного, показанного положения?",
    ),
    visual: custom("lShapeRotation"),
    options: [
      { id: "A", text: P("Rotated 180° from start", "Повёрнута на 180° от начального положения") },
      { id: "B", text: P("Same as start", "Как в начале") },
      { id: "C", text: P("Rotated 90° from start", "Повёрнута на 90° от начального положения") },
      { id: "D", text: P("Rotated 270° from start", "Повёрнута на 270° от начального положения") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Six rotations of 90° total 540°. 540° − 360° = 180°, so the tile is rotated 180° from its starting orientation.",
      "Шесть поворотов по 90° дают в сумме 540°. 540° − 360° = 180°, значит плитка повёрнута на 180° от начального положения.",
    ),
    weight: 1.5,
  },
  {
    id: 420,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "A shape is reflected vertically, then rotated 90° clockwise, then reflected vertically again. Starting from an arrow pointing right, in which direction does it now point?",
      "Фигуру отражают по вертикали, затем поворачивают на 90° по часовой стрелке, затем снова отражают по вертикали. Если исходно стрелка указывала вправо, куда она указывает теперь?",
    ),
    options: [
      { id: "A", text: P("Up", "Вверх") },
      { id: "B", text: P("Down", "Вниз") },
      { id: "C", text: P("Left", "Влево") },
      { id: "D", text: P("Right", "Вправо") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Right → reflect vertically (flip up-down) → right stays right (a horizontal arrow is unaffected by a vertical flip). Rotate 90° clockwise → right becomes down. Reflect vertically again → down becomes up. Final direction: up.",
      "Вправо → отражение по вертикали (переворот вверх-вниз) → горизонтальная стрелка не меняется, остаётся «вправо». Поворот на 90° по часовой стрелке → «вправо» становится «вниз». Повторное отражение по вертикали → «вниз» становится «вверх». Итоговое направление: вверх.",
    ),
    weight: 2,
  },
  {
    id: 421,
    category: "spatial",
    difficulty: "easy",
    prompt: P(
      "The arrow rotates 180° each step. What is the next direction?",
      "Стрелка поворачивается на 180° на каждом шаге. Каково следующее направление?",
    ),
    visual: arrow([0, 180, 0, 180, "blank"]),
    options: [
      { id: "A", text: P("Pointing right (0°)", "Вправо (0°)") },
      { id: "B", text: P("Pointing left (180°)", "Влево (180°)") },
      { id: "C", text: P("Pointing up (90°)", "Вверх (90°)") },
      { id: "D", text: P("Pointing down (270°)", "Вниз (270°)") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Rotating 180° each step flips the arrow between right and left. After the fourth step (180°) comes right, so the fifth step returns to left... following the shown pattern 0,180,0,180, the next value is 180°: pointing left.",
      "Поворот на 180° на каждом шаге переключает стрелку между «вправо» и «влево». Согласно показанной последовательности 0,180,0,180, следующее значение — 180°: указывает влево.",
    ),
    weight: 1,
  },
  {
    id: 422,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "You view a 4×4×4 cube made of 64 small cubes. All outer faces are painted blue. If disassembled, how many small cubes have exactly 0 painted faces (fully interior)?",
      "Вы рассматриваете куб 4×4×4 из 64 маленьких кубиков. Все внешние грани окрашены в синий. Если куб разобрать, сколько кубиков не будут иметь ни одной окрашенной грани (полностью внутренние)?",
    ),
    options: [
      { id: "A", text: P("8", "8") },
      { id: "B", text: P("16", "16") },
      { id: "C", text: P("24", "24") },
      { id: "D", text: P("4", "4") },
    ],
    correctAnswer: "A",
    explanation: P(
      "The fully interior cubes form a smaller (4−2)×(4−2)×(4−2) = 2×2×2 = 8 cube block untouched by any outer face.",
      "Полностью внутренние кубики образуют меньший блок (4−2)×(4−2)×(4−2) = 2×2×2 = 8 кубиков, не соприкасающийся ни с одной внешней гранью.",
    ),
    weight: 2,
  },
  {
    id: 423,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "The arrow rotates 60° clockwise each step. What is the direction after the pattern shown continues one more step?",
      "Стрелка поворачивается на 60° по часовой стрелке на каждом шаге. Каково направление, если показанный узор продолжится ещё на один шаг?",
    ),
    visual: arrow([0, 60, 120, 180, 240, "blank"]),
    options: [
      { id: "A", text: P("300°", "300°") },
      { id: "B", text: P("270°", "270°") },
      { id: "C", text: P("360° (0°)", "360° (0°)") },
      { id: "D", text: P("320°", "320°") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Each step adds 60°. 240° + 60° = 300°.",
      "Каждый шаг добавляет 60°. 240° + 60° = 300°.",
    ),
    weight: 1.5,
  },
  {
    id: 424,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "In the cross-shaped cube net (faces numbered 1–6 as in the standard layout, 1 at the top of the vertical arm and 6 at the bottom), which pair of faces are adjacent (share an edge) rather than opposite after folding?",
      "В развёртке куба в виде креста (грани пронумерованы 1–6, как в стандартном варианте: 1 сверху вертикальной полосы, 6 снизу), какая пара граней будет соседней (иметь общее ребро), а не противоположной после складывания?",
    ),
    visual: custom("cubeNetCross"),
    options: [
      { id: "A", text: P("2 and 3", "2 и 3") },
      { id: "B", text: P("1 and 6", "1 и 6") },
      { id: "C", text: P("2 and 4", "2 и 4") },
      { id: "D", text: P("3 and 5", "3 и 5") },
    ],
    correctAnswer: "A",
    explanation: P(
      "In the cross net, faces 2, 3, 4, and 5 form the horizontal band wrapping around the cube's sides, so consecutive faces like 2 and 3 end up sharing an edge. Faces 1 and 6 (top and bottom of the vertical arm) end up opposite each other, not adjacent.",
      "В развёртке-кресте грани 2, 3, 4 и 5 образуют горизонтальную полосу, оборачивающую боковые стороны куба, поэтому соседние грани, например 2 и 3, имеют общее ребро. Грани 1 и 6 (верх и низ вертикальной полосы) оказываются противоположными, а не соседними.",
    ),
    weight: 2,
  },
  {
    id: 425,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "A rectangular sheet of paper is folded in half once (bringing the short edges together) and a hole is punched through both layers near the fold. How many holes appear when unfolded?",
      "Прямоугольный лист бумаги складывают пополам один раз (совмещая короткие края) и пробивают отверстие через оба слоя у сгиба. Сколько отверстий появится при разворачивании?",
    ),
    visual: custom("paperFold2x"),
    options: [
      { id: "A", text: P("2", "2") },
      { id: "B", text: P("1", "1") },
      { id: "C", text: P("4", "4") },
      { id: "D", text: P("3", "3") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A single fold creates 2 layers of paper. One punch through both layers produces 2 holes when unfolded, mirrored across the fold line.",
      "Один сгиб создаёт 2 слоя бумаги. Один прокол через оба слоя даёт 2 отверстия при разворачивании, симметричных относительно линии сгиба.",
    ),
    weight: 1.5,
  },
  {
    id: 426,
    category: "spatial",
    difficulty: "easy",
    prompt: P(
      "The arrow rotates 90° clockwise each step, but the sequence shown starts at 90° instead of 0°. What comes next?",
      "Стрелка поворачивается на 90° по часовой стрелке на каждом шаге, но показанная последовательность начинается с 90°, а не с 0°. Что дальше?",
    ),
    visual: arrow([90, 180, 270, 0, "blank"]),
    options: [
      { id: "A", text: P("90°", "90°") },
      { id: "B", text: P("180°", "180°") },
      { id: "C", text: P("0°", "0°") },
      { id: "D", text: P("270°", "270°") },
    ],
    correctAnswer: "A",
    explanation: P(
      "The 90° clockwise cycle is 90°→180°→270°→0°→90°. After 0° comes back to 90°.",
      "Цикл поворота на 90° по часовой стрелке: 90°→180°→270°→0°→90°. После 0° снова 90°.",
    ),
    weight: 1,
  },
  {
    id: 427,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "A cube has faces marked 1 through 6 (opposite faces sum to 7). It is rolled one quarter-turn to the right (east) so the face that was facing right is now facing down. If 3 was facing you and 5 was on top before rolling, what face is on top after rolling?",
      "На кубе грани отмечены от 1 до 6 (противоположные грани в сумме дают 7). Его прокатывают на четверть оборота вправо (на восток), так что грань, которая была справа, теперь снизу. Если до прокатывания грань 3 была обращена к вам, а грань 5 была сверху, какая грань сверху после прокатывания?",
    ),
    visual: custom("standardDie"),
    options: [
      { id: "A", text: P("The face that was on the left", "Грань, которая была слева") },
      { id: "B", text: P("The face that was on the right", "Грань, которая была справа") },
      { id: "C", text: P("The face that was facing you", "Грань, которая была обращена к вам") },
      { id: "D", text: P("The face that was on the bottom", "Грань, которая была снизу") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Rolling a cube a quarter-turn to the right moves: top→right, right→bottom, bottom→left, left→top. So the face that ends up on top is the one that was previously on the left.",
      "При прокатывании куба на четверть оборота вправо грани смещаются: верх→право, право→низ, низ→лево, лево→верх. Значит сверху оказывается грань, которая раньше была слева.",
    ),
    weight: 2,
  },
  {
    id: 428,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "The arrow rotates 45° counter-clockwise each step. Starting at 90° (up), what direction is it after 3 steps?",
      "Стрелка поворачивается на 45° против часовой стрелки на каждом шаге. Начиная с 90° (вверх), каково направление после 3 шагов?",
    ),
    options: [
      { id: "A", text: P("225°", "225°") },
      { id: "B", text: P("180°", "180°") },
      { id: "C", text: P("270°", "270°") },
      { id: "D", text: P("315°", "315°") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Counter-clockwise rotation increases the angle: 90° + 3×45° = 90° + 135° = 225°.",
      "Поворот против часовой стрелки увеличивает угол: 90° + 3×45° = 90° + 135° = 225°.",
    ),
    weight: 1.5,
  },
  {
    id: 429,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "A large tetrahedron is built from 27 identical small tetrahedra stacked in a triangular pyramid arrangement (3 layers: 1, 3+3, and the rest at the base, totaling 27 small pieces where each edge of the large shape is divided into 3 equal parts). If the outer surface is painted, how many small tetrahedra have paint on more than one face?",
      "Большой тетраэдр собран из 27 одинаковых маленьких тетраэдров, уложенных в форме треугольной пирамиды (каждое ребро большой фигуры разделено на 3 равные части). Если внешнюю поверхность покрасить, у скольких маленьких тетраэдров окажется краска более чем на одной грани?",
    ),
    options: [
      { id: "A", text: P("This requires counting each corner and edge piece individually — it cannot be answered with a single simple formula the way a cube can.", "Это требует индивидуального подсчёта каждого углового и рёберного элемента — единой простой формулы, как для куба, здесь нет.") },
      { id: "B", text: P("Exactly 8, by direct analogy with a cube", "Ровно 8, по прямой аналогии с кубом") },
      { id: "C", text: P("Exactly 12, by direct analogy with a cube", "Ровно 12, по прямой аналогии с кубом") },
      { id: "D", text: P("Exactly 27, all of them", "Ровно 27, все") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Unlike a cube, a tetrahedron's corner and edge piece counts don't follow the same simple pattern, since a tetrahedron has only 4 corners and 6 edges with different geometry — a direct cube analogy (8 corners, 12 edges) does not apply, making careful individual analysis of the specific solid necessary rather than a shortcut formula.",
      "В отличие от куба, число угловых и рёберных элементов тетраэдра не подчиняется той же простой закономерности, так как у тетраэдра всего 4 вершины и 6 рёбер с иной геометрией — прямая аналогия с кубом (8 углов, 12 рёбер) не подходит, и требуется тщательный индивидуальный анализ именно этой фигуры, а не готовая формула.",
    ),
    weight: 2,
  },
  {
    id: 430,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "An L-shaped tile is reflected horizontally, then rotated 90° clockwise. If it started pointing with its foot to the right, where does the foot point now?",
      "L-образную плитку отражают по горизонтали, затем поворачивают на 90° по часовой стрелке. Если изначально её «нога» указывала вправо, куда она указывает теперь?",
    ),
    visual: custom("lShapeRotation"),
    options: [
      { id: "A", text: P("Up", "Вверх") },
      { id: "B", text: P("Down", "Вниз") },
      { id: "C", text: P("Left", "Влево") },
      { id: "D", text: P("Right", "Вправо") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Right → reflect horizontally (flip left-right) → left. Rotate 90° clockwise → left becomes up.",
      "Вправо → отражение по горизонтали (переворот влево-вправо) → влево. Поворот на 90° по часовой стрелке → «влево» становится «вверх».",
    ),
    weight: 1.5,
  },
  {
    id: 431,
    category: "spatial",
    difficulty: "easy",
    prompt: P(
      "The arrow rotates 90° counter-clockwise each step, starting at 180° (left). What is the next direction?",
      "Стрелка поворачивается на 90° против часовой стрелки на каждом шаге, начиная с 180° (влево). Каково следующее направление?",
    ),
    visual: arrow([180, 90, 0, 270, "blank"]),
    options: [
      { id: "A", text: P("180°", "180°") },
      { id: "B", text: P("90°", "90°") },
      { id: "C", text: P("0°", "0°") },
      { id: "D", text: P("270°", "270°") },
    ],
    correctAnswer: "A",
    explanation: P(
      "The cycle 180°→90°→0°→270°→180° repeats every 4 steps. After 270° comes back to 180°.",
      "Цикл 180°→90°→0°→270°→180° повторяется каждые 4 шага. После 270° снова 180°.",
    ),
    weight: 1,
  },
  {
    id: 432,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "A shape is rotated 90° counter-clockwise, then rotated 90° clockwise, then reflected vertically. Starting from an arrow pointing down, in which direction does it now point?",
      "Фигуру поворачивают на 90° против часовой стрелки, затем на 90° по часовой стрелке, затем отражают по вертикали. Если исходно стрелка указывала вниз, куда она указывает теперь?",
    ),
    options: [
      { id: "A", text: P("Up", "Вверх") },
      { id: "B", text: P("Down", "Вниз") },
      { id: "C", text: P("Left", "Влево") },
      { id: "D", text: P("Right", "Вправо") },
    ],
    correctAnswer: "A",
    explanation: P(
      "The two opposite 90° rotations cancel out, leaving the arrow still pointing down. Reflecting vertically (flip up-down) turns down into up.",
      "Два противоположных поворота на 90° взаимно компенсируются, стрелка остаётся направленной вниз. Отражение по вертикали (переворот вверх-вниз) превращает «вниз» в «вверх».",
    ),
    weight: 2,
  },
  {
    id: 433,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "You view a 3×3×3 cube made of 27 small cubes. All outer faces are painted green. If disassembled, how many small cubes have exactly 1 painted face?",
      "Вы рассматриваете куб 3×3×3 из 27 маленьких кубиков. Все внешние грани окрашены в зелёный. Если куб разобрать, сколько кубиков будут иметь ровно 1 окрашенную грань?",
    ),
    options: [
      { id: "A", text: P("6", "6") },
      { id: "B", text: P("8", "8") },
      { id: "C", text: P("12", "12") },
      { id: "D", text: P("1", "1") },
    ],
    correctAnswer: "A",
    explanation: P(
      "In a 3×3×3 painted cube, the face-center cubes (one per face, in the middle of each 3×3 face) have exactly 1 painted face. There are 6 faces, so 6 such cubes.",
      "В окрашенном кубе 3×3×3 кубики в центре каждой грани (по одному на грань) имеют ровно 1 окрашенную грань. Всего 6 граней, значит таких кубиков 6.",
    ),
    weight: 1.5,
  },
  {
    id: 434,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "A square sheet of paper is folded diagonally in half once (corner to corner) and a hole is punched through both layers away from the fold line. How many holes appear when unfolded?",
      "Квадратный лист бумаги складывают по диагонали пополам один раз (угол к углу) и пробивают отверстие через оба слоя вдали от линии сгиба. Сколько отверстий появится при разворачивании?",
    ),
    visual: custom("paperFold2x"),
    options: [
      { id: "A", text: P("2", "2") },
      { id: "B", text: P("1", "1") },
      { id: "C", text: P("4", "4") },
      { id: "D", text: P("0", "0") },
    ],
    correctAnswer: "A",
    explanation: P(
      "One fold always creates 2 layers of paper regardless of fold direction (straight or diagonal). Punching through both layers produces 2 holes, mirrored across the fold line, when unfolded.",
      "Один сгиб всегда создаёт 2 слоя бумаги, независимо от направления складывания (прямого или диагонального). Прокол через оба слоя даёт 2 отверстия, симметричных относительно линии сгиба, при разворачивании.",
    ),
    weight: 1.5,
  },
  {
    id: 435,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "In the cross-shaped cube net (faces 1–6, 1 at top of the vertical arm, 6 at bottom, with 2, 3, 4, 5 forming the horizontal band in that left-to-right order), which face ends up opposite face 3?",
      "В развёртке куба в виде креста (грани 1–6, 1 сверху вертикальной полосы, 6 снизу, а 2, 3, 4, 5 образуют горизонтальную полосу именно в этом порядке слева направо), какая грань окажется напротив грани 3?",
    ),
    visual: custom("cubeNetCross"),
    options: [
      { id: "A", text: P("5", "5") },
      { id: "B", text: P("2", "2") },
      { id: "C", text: P("4", "4") },
      { id: "D", text: P("1", "1") },
    ],
    correctAnswer: "A",
    explanation: P(
      "In the horizontal band of 4 consecutive faces (2, 3, 4, 5) wrapping around the cube, the faces two positions apart end up opposite each other: face 3 ends up opposite face 5.",
      "В горизонтальной полосе из 4 последовательных граней (2, 3, 4, 5), оборачивающей куб, грани, отстоящие друг от друга на 2 позиции, оказываются противоположными: грань 3 оказывается напротив грани 5.",
    ),
    weight: 2,
  },
  {
    id: 436,
    category: "spatial",
    difficulty: "easy",
    prompt: P(
      "The arrow rotates 90° clockwise each step, but two steps are shown skipping ahead. If the first shown position is 0° and the third is 180°, what fills the missing second position?",
      "Стрелка поворачивается на 90° по часовой стрелке на каждом шаге, но показаны два шага с пропуском. Если первое показанное положение — 0°, а третье — 180°, что должно быть на пропущенной второй позиции?",
    ),
    visual: arrow([0, "blank", 180, 270]),
    options: [
      { id: "A", text: P("90°", "90°") },
      { id: "B", text: P("45°", "45°") },
      { id: "C", text: P("135°", "135°") },
      { id: "D", text: P("270°", "270°") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since each step adds 90° and position 1 is 0° while position 3 is 180° (two steps later, 0°+90°+90°=180°, consistent), position 2 must be the halfway step: 0° + 90° = 90°.",
      "Так как каждый шаг добавляет 90°, а позиция 1 — это 0°, позиция 3 — 180° (два шага спустя: 0°+90°+90°=180°, что верно), позиция 2 должна быть промежуточным шагом: 0° + 90° = 90°.",
    ),
    weight: 1,
  },
  {
    id: 437,
    category: "spatial",
    difficulty: "medium",
    prompt: P(
      "A cube has faces marked 1 through 6 (opposite faces sum to 7). The cube is flipped forward (rolled toward you) so the face that was facing you is now on top. If 4 was facing you and 1 was on top before flipping, what face is on top after flipping?",
      "На кубе грани отмечены от 1 до 6 (противоположные грани в сумме дают 7). Куб перекатывают вперёд (на себя), так что грань, обращённая к вам, теперь сверху. Если до переворота грань 4 была обращена к вам, а грань 1 — сверху, какая грань сверху после переворота?",
    ),
    visual: custom("standardDie"),
    options: [
      { id: "A", text: P("4", "4") },
      { id: "B", text: P("3", "3") },
      { id: "C", text: P("1", "1") },
      { id: "D", text: P("6", "6") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Rolling a cube forward (toward you) moves: front→top, top→back, back→bottom, bottom→front. So the face that was facing you (4) ends up on top.",
      "При перекатывании куба вперёд (на себя) грани смещаются: перед→верх, верх→зад, зад→низ, низ→перед. Значит грань, которая была обращена к вам (4), оказывается сверху.",
    ),
    weight: 1.5,
  },
  {
    id: 438,
    category: "spatial",
    difficulty: "hard",
    prompt: P(
      "You view a 5×5×5 cube made of 125 small cubes. All outer faces are painted yellow. If disassembled, how many small cubes have exactly 2 painted faces (edge pieces, not corners)?",
      "Вы рассматриваете куб 5×5×5 из 125 маленьких кубиков. Все внешние грани окрашены в жёлтый. Если куб разобрать, сколько кубиков будут иметь ровно 2 окрашенные грани (рёберные, не угловые)?",
    ),
    options: [
      { id: "A", text: P("36", "36") },
      { id: "B", text: P("12", "12") },
      { id: "C", text: P("54", "54") },
      { id: "D", text: P("8", "8") },
    ],
    correctAnswer: "A",
    explanation: P(
      "A cube has 12 edges. On an n×n×n cube, each edge (excluding corners) has (n−2) two-face cubes. For n=5: (5−2)=3 per edge × 12 edges = 36.",
      "У куба 12 рёбер. На кубе n×n×n на каждом ребре (без учёта углов) находится (n−2) кубика с двумя окрашенными гранями. Для n=5: (5−2)=3 на ребро × 12 рёбер = 36.",
    ),
    weight: 2,
  },
];
