import type { ToolIconProps } from "@/components/icons/ToolIcons";
import {
  SunburstIcon,
  SparkleIcon,
  MoonSymbolIcon,
  FeatherSymbolIcon,
  WaveSymbolIcon,
  MountainSymbolIcon,
  FlameSymbolIcon,
  KeySymbolIcon,
  AnchorSymbolIcon,
  CompassSymbolIcon,
  LeafSymbolIcon,
  LanternSymbolIcon,
  CrystalBallIcon,
} from "@/components/icons/ToolIcons";

export type DailyReadingLocale = "en" | "ru";

export interface SymbolEntry {
  name: string;
  meaning: string;
  /** Called directly as a function (`entry.icon({ className })`) rather
   * than used as a JSX tag, since the icon reference is a plain data
   * field passed through a data pool rather than a static import at
   * the call site. */
  icon: (props: ToolIconProps) => React.ReactElement;
}

export interface ColorEntry {
  name: string;
  hex: string;
  meaning: string;
}

/**
 * Content pools for the Daily Reading tool. Every list intentionally
 * has 20-30+ entries so the daily result feels genuinely varied across
 * a month, not a small rotating set. Text is deliberately reflective /
 * mood-setting rather than predictive ("a theme to notice today"), in
 * line with the same entertainment-only framing used by the rest of
 * the fortune tools.
 */

export const energiesEn: readonly string[] = [
  "Quiet Renewal", "Bold Momentum", "Gentle Curiosity", "Steady Focus",
  "Playful Spark", "Grounded Calm", "Open Heart", "Sharp Clarity",
  "Warm Connection", "Restless Drive", "Soft Patience", "Bright Optimism",
  "Deep Reflection", "Fresh Perspective", "Quiet Confidence", "Creative Flow",
  "Gentle Release", "Steady Courage", "Light Curiosity", "Inner Balance",
  "Rising Energy", "Calm Determination", "Tender Honesty", "Vivid Imagination",
  "Grounded Trust", "Playful Wonder", "Focused Ambition", "Peaceful Acceptance",
  "Warm Generosity", "Quiet Strength", "Bright Renewal", "Gentle Momentum",
];

export const energiesRu: readonly string[] = [
  "Тихое обновление", "Смелый порыв", "Мягкое любопытство", "Устойчивая сосредоточенность",
  "Игривая искра", "Спокойная уверенность", "Открытое сердце", "Ясная чёткость",
  "Тёплая связь", "Беспокойная энергия", "Мягкое терпение", "Светлый оптимизм",
  "Глубокое размышление", "Свежий взгляд", "Тихая уверенность в себе", "Творческий поток",
  "Мягкое отпускание", "Спокойная смелость", "Лёгкое любопытство", "Внутренний баланс",
  "Восходящая энергия", "Спокойная решимость", "Нежная честность", "Яркое воображение",
  "Уверенное доверие", "Игривое удивление", "Сфокусированные амбиции", "Мирное принятие",
  "Тёплая щедрость", "Тихая сила", "Светлое обновление", "Мягкий импульс",
];

export const symbolsEn: readonly SymbolEntry[] = [
  { name: "Crescent Moon", meaning: "a cycle quietly turning toward something new", icon: MoonSymbolIcon },
  { name: "Night Sky", meaning: "space to slow down and simply notice", icon: MoonSymbolIcon },
  { name: "Feather", meaning: "something you can carry lightly today", icon: FeatherSymbolIcon },
  { name: "Rising Bird", meaning: "a small chance to lift your perspective", icon: FeatherSymbolIcon },
  { name: "Ocean Wave", meaning: "a feeling that comes and goes in its own time", icon: WaveSymbolIcon },
  { name: "Still Water", meaning: "clarity that comes from pausing, not pushing", icon: WaveSymbolIcon },
  { name: "Mountain Peak", meaning: "a goal worth the slow climb", icon: MountainSymbolIcon },
  { name: "Distant Horizon", meaning: "a reminder that the bigger picture is still forming", icon: MountainSymbolIcon },
  { name: "Candle Flame", meaning: "a small idea worth protecting from doubt", icon: FlameSymbolIcon },
  { name: "Warm Ember", meaning: "motivation that's steadier than it looks", icon: FlameSymbolIcon },
  { name: "Old Key", meaning: "something from the past worth revisiting", icon: KeySymbolIcon },
  { name: "Open Door", meaning: "an invitation you might be underestimating", icon: KeySymbolIcon },
  { name: "Anchor", meaning: "a person or habit that's steadying you right now", icon: AnchorSymbolIcon },
  { name: "Compass", meaning: "a decision that needs your own direction, not someone else's", icon: CompassSymbolIcon },
  { name: "Guiding Star", meaning: "a value you keep coming back to", icon: SparkleIcon },
  { name: "Falling Star", meaning: "a wish worth naming out loud, even quietly", icon: SparkleIcon },
  { name: "New Leaf", meaning: "a small, low-pressure fresh start", icon: LeafSymbolIcon },
  { name: "Old Oak", meaning: "patience with something that's still growing", icon: LeafSymbolIcon },
  { name: "Lantern", meaning: "a bit of guidance you already have, if you look", icon: LanternSymbolIcon },
  { name: "Glowing Window", meaning: "somewhere (or someone) worth checking in on", icon: LanternSymbolIcon },
  { name: "Crystal Sphere", meaning: "a question that deserves sitting with, not rushing", icon: CrystalBallIcon },
  { name: "Morning Sun", meaning: "energy that's better used early than saved for later", icon: SunburstIcon },
  { name: "Golden Hour", meaning: "a short window worth paying closer attention to", icon: SunburstIcon },
  { name: "Winding Path", meaning: "progress that doesn't need to be a straight line", icon: CompassSymbolIcon },
  { name: "Quiet River", meaning: "steady movement, even when it's not dramatic", icon: WaveSymbolIcon },
  { name: "Blank Page", meaning: "room to define something on your own terms", icon: LeafSymbolIcon },
  { name: "Twin Flame Pair", meaning: "a connection that benefits from honesty today", icon: FlameSymbolIcon },
  { name: "Hidden Root", meaning: "support that's working quietly, out of sight", icon: MountainSymbolIcon },
  { name: "Clear Sky", meaning: "less to worry about than it might feel like", icon: SunburstIcon },
  { name: "Paper Boat", meaning: "a small plan worth just letting float for now", icon: WaveSymbolIcon },
];

export const symbolsRu: readonly SymbolEntry[] = [
  { name: "Молодой месяц", meaning: "цикл, который тихо разворачивается к новому", icon: MoonSymbolIcon },
  { name: "Ночное небо", meaning: "пространство, чтобы замедлиться и просто заметить", icon: MoonSymbolIcon },
  { name: "Пёрышко", meaning: "что-то, что сегодня можно нести легко", icon: FeatherSymbolIcon },
  { name: "Взлетающая птица", meaning: "маленький шанс изменить угол зрения", icon: FeatherSymbolIcon },
  { name: "Морская волна", meaning: "чувство, которое приходит и уходит в своё время", icon: WaveSymbolIcon },
  { name: "Тихая вода", meaning: "ясность, что приходит от паузы, а не от спешки", icon: WaveSymbolIcon },
  { name: "Горная вершина", meaning: "цель, ради которой стоит подниматься медленно", icon: MountainSymbolIcon },
  { name: "Дальний горизонт", meaning: "напоминание, что общая картина ещё складывается", icon: MountainSymbolIcon },
  { name: "Пламя свечи", meaning: "маленькая идея, которую стоит защитить от сомнений", icon: FlameSymbolIcon },
  { name: "Тёплый уголёк", meaning: "мотивация надёжнее, чем кажется", icon: FlameSymbolIcon },
  { name: "Старый ключ", meaning: "то из прошлого, к чему стоит вернуться", icon: KeySymbolIcon },
  { name: "Открытая дверь", meaning: "приглашение, которое ты, возможно, недооцениваешь", icon: KeySymbolIcon },
  { name: "Якорь", meaning: "человек или привычка, которые сейчас тебя держат", icon: AnchorSymbolIcon },
  { name: "Компас", meaning: "решение, для которого нужно твоё собственное направление", icon: CompassSymbolIcon },
  { name: "Путеводная звезда", meaning: "ценность, к которой ты постоянно возвращаешься", icon: SparkleIcon },
  { name: "Падающая звезда", meaning: "желание, которое стоит назвать, пусть даже тихо", icon: SparkleIcon },
  { name: "Молодой лист", meaning: "небольшое начало без лишнего давления", icon: LeafSymbolIcon },
  { name: "Старый дуб", meaning: "терпение к тому, что всё ещё растёт", icon: LeafSymbolIcon },
  { name: "Фонарь", meaning: "немного подсказки, которая у тебя уже есть", icon: LanternSymbolIcon },
  { name: "Светящееся окно", meaning: "место (или человек), о ком стоит узнать", icon: LanternSymbolIcon },
  { name: "Хрустальный шар", meaning: "вопрос, который заслуживает раздумья, а не спешки", icon: CrystalBallIcon },
  { name: "Утреннее солнце", meaning: "энергия, которую лучше использовать сейчас, а не откладывать", icon: SunburstIcon },
  { name: "Золотой час", meaning: "короткое окно, которому стоит уделить внимание", icon: SunburstIcon },
  { name: "Извилистая тропа", meaning: "прогресс не обязан быть прямой линией", icon: CompassSymbolIcon },
  { name: "Тихая река", meaning: "устойчивое движение, даже без драмы", icon: WaveSymbolIcon },
  { name: "Чистый лист", meaning: "пространство, чтобы решить что-то по-своему", icon: LeafSymbolIcon },
  { name: "Двойное пламя", meaning: "связь, которой сегодня пойдёт на пользу честность", icon: FlameSymbolIcon },
  { name: "Скрытый корень", meaning: "опора, что работает тихо, вне поля зрения", icon: MountainSymbolIcon },
  { name: "Чистое небо", meaning: "поводов для тревоги меньше, чем кажется", icon: SunburstIcon },
  { name: "Бумажный кораблик", meaning: "маленький план, который пока стоит просто отпустить", icon: WaveSymbolIcon },
];

export const colorsEn: readonly ColorEntry[] = [
  { name: "Deep Indigo", hex: "#3F3D8C", meaning: "insight" },
  { name: "Soft Lavender", hex: "#B9A6DC", meaning: "ease" },
  { name: "Warm Amber", hex: "#E0A438", meaning: "encouragement" },
  { name: "Sea Teal", hex: "#2E9E9E", meaning: "steadiness" },
  { name: "Rose Quartz", hex: "#E7A8B0", meaning: "gentleness" },
  { name: "Forest Green", hex: "#3C7A5A", meaning: "growth" },
  { name: "Midnight Blue", hex: "#233A66", meaning: "focus" },
  { name: "Sunset Coral", hex: "#E8795B", meaning: "warmth" },
  { name: "Pale Gold", hex: "#D9C06A", meaning: "confidence" },
  { name: "Slate Grey", hex: "#7C8894", meaning: "clarity" },
  { name: "Plum Violet", hex: "#6E4A6E", meaning: "depth" },
  { name: "Sky Blue", hex: "#7FB6D9", meaning: "openness" },
  { name: "Terracotta", hex: "#BE6A47", meaning: "resilience" },
  { name: "Ivory White", hex: "#EFE9DD", meaning: "a clean slate" },
  { name: "Charcoal", hex: "#3A3A3E", meaning: "grounding" },
  { name: "Honey Yellow", hex: "#DFB13C", meaning: "optimism" },
  { name: "Dusty Rose", hex: "#C98E92", meaning: "self-compassion" },
  { name: "Emerald", hex: "#2E8B65", meaning: "renewal" },
  { name: "Copper", hex: "#B5713C", meaning: "quiet momentum" },
  { name: "Deep Teal", hex: "#1F5F5B", meaning: "calm resolve" },
  { name: "Soft Peach", hex: "#EFC1A0", meaning: "comfort" },
  { name: "Storm Grey", hex: "#5B6470", meaning: "honesty" },
];

export const colorsRu: readonly ColorEntry[] = [
  { name: "Глубокий индиго", hex: "#3F3D8C", meaning: "проницательность" },
  { name: "Мягкая лаванда", hex: "#B9A6DC", meaning: "лёгкость" },
  { name: "Тёплый янтарь", hex: "#E0A438", meaning: "поддержка" },
  { name: "Морской бирюзовый", hex: "#2E9E9E", meaning: "устойчивость" },
  { name: "Розовый кварц", hex: "#E7A8B0", meaning: "мягкость" },
  { name: "Лесной зелёный", hex: "#3C7A5A", meaning: "рост" },
  { name: "Полуночный синий", hex: "#233A66", meaning: "сосредоточенность" },
  { name: "Закатный коралл", hex: "#E8795B", meaning: "теплота" },
  { name: "Бледное золото", hex: "#D9C06A", meaning: "уверенность" },
  { name: "Сланцевый серый", hex: "#7C8894", meaning: "ясность" },
  { name: "Сливовый фиолетовый", hex: "#6E4A6E", meaning: "глубина" },
  { name: "Небесно-голубой", hex: "#7FB6D9", meaning: "открытость" },
  { name: "Терракотовый", hex: "#BE6A47", meaning: "стойкость" },
  { name: "Слоновая кость", hex: "#EFE9DD", meaning: "чистый лист" },
  { name: "Угольный", hex: "#3A3A3E", meaning: "заземление" },
  { name: "Медовый жёлтый", hex: "#DFB13C", meaning: "оптимизм" },
  { name: "Пыльная роза", hex: "#C98E92", meaning: "забота о себе" },
  { name: "Изумрудный", hex: "#2E8B65", meaning: "обновление" },
  { name: "Медный", hex: "#B5713C", meaning: "тихий импульс" },
  { name: "Глубокий бирюзовый", hex: "#1F5F5B", meaning: "спокойная решимость" },
  { name: "Мягкий персиковый", hex: "#EFC1A0", meaning: "комфорт" },
  { name: "Грозовой серый", hex: "#5B6470", meaning: "честность" },
];

export const focusesEn: readonly string[] = [
  "Say the honest thing, kindly", "Finish one small task fully", "Ask instead of assuming",
  "Rest before you're exhausted", "Notice one thing you're grateful for", "Let a plan stay unfinished for now",
  "Reach out to someone you've been meaning to", "Choose progress over perfection",
  "Protect your energy for what matters", "Try the idea you've been putting off",
  "Listen a little longer than usual", "Say no without over-explaining",
  "Celebrate a small win out loud", "Give yourself the benefit of the doubt",
  "Simplify one thing that's gotten complicated", "Spend time somewhere that calms you",
  "Write down the thought that keeps circling", "Do the thing you'd tell a friend to do",
  "Take the smaller, steadier step", "Forgive a small mistake — yours or theirs",
  "Make space before saying yes", "Notice what's already working",
  "Trust the plan you already made", "Let curiosity lead for an hour",
  "Check in with your body, not just your calendar", "Close one open loop today",
  "Speak up for what you actually want", "Give a compliment you're holding back",
  "Slow down the next decision by five minutes", "Do something with your hands, not your phone",
  "Revisit a goal you haven't looked at in a while", "Let today be enough, without comparison",
];

export const focusesRu: readonly string[] = [
  "Скажи честно, но по-доброму", "Доведи одно маленькое дело до конца", "Спроси, а не предполагай",
  "Отдохни до того, как устанешь", "Заметь одну вещь, за которую благодарен(на)", "Оставь план незавершённым на время",
  "Напиши тому, кому давно собирался(лась)", "Выбери прогресс, а не идеал",
  "Береги свою энергию для важного", "Попробуй ту идею, что откладывал(а)",
  "Слушай чуть дольше обычного", "Скажи «нет» без лишних объяснений",
  "Отметь маленькую победу вслух", "Дай себе право на сомнение",
  "Упрости то, что стало слишком сложным", "Побудь там, где тебе спокойно",
  "Запиши мысль, что не отпускает", "Сделай то, что посоветовал(а) бы другу",
  "Сделай меньший, но увереннный шаг", "Прости маленькую ошибку — свою или чужую",
  "Дай себе паузу перед тем, как согласиться", "Заметь, что уже получается",
  "Доверься плану, который уже есть", "Дай любопытству повести тебя час",
  "Прислушайся к телу, а не только к календарю", "Закрой сегодня одно незавершённое дело",
  "Скажи, чего ты действительно хочешь", "Сделай комплимент, который держишь при себе",
  "Отложи следующее решение на пять минут", "Сделай что-то руками, а не с телефоном",
  "Вернись к цели, о которой давно не думал(а)", "Пусть сегодняшний день будет достаточным, без сравнений",
];

export const messagesEn: readonly string[] = [
  "Today rewards small, honest steps more than big, dramatic ones.",
  "Something you've been overthinking is simpler than it feels right now.",
  "A short pause today will save you a longer one later.",
  "You don't need to have it all figured out by tonight.",
  "The version of today that goes well starts with being kind to yourself first.",
  "A conversation you've been avoiding is more ready than you think.",
  "Not every open question needs an answer today — some can just stay open.",
  "You're closer to a small breakthrough than the last few days made it feel.",
  "Today favors doing the next right thing over the perfect thing.",
  "Something quiet is working in your favor, even if it's not visible yet.",
  "You have more say in how today goes than it might seem this morning.",
  "A little structure today will feel like relief, not restriction.",
  "The thing you're nervous about is smaller once you actually start it.",
  "Today is a good day to trust your first instinct a little more.",
  "Someone nearby could use exactly the kind of attention you're good at giving.",
  "A small act of patience today prevents a bigger frustration tomorrow.",
  "You're allowed to enjoy something today without justifying it.",
  "The plan doesn't need to be perfect — it needs to start.",
  "What feels like a setback today is more likely a redirection.",
  "Today, less explaining and more doing will serve you well.",
  "A little honesty with yourself today clears up more than it costs.",
  "You're being asked to choose steadiness over speed today.",
  "The energy you bring into the first hour tends to shape the rest of today.",
  "Something you finish today will matter more next week than it feels like now.",
  "Today has room for one meaningful thing, not ten scattered ones.",
  "A boundary you set today will feel awkward for a minute and helpful after.",
  "You've already done the hard part — today is about following through.",
  "Someone's opinion of you today says more about them than about you.",
  "A small kindness today costs little and travels further than expected.",
  "Today, the quieter option is probably the wiser one.",
  "You're allowed to change your mind about something today.",
  "The thing you keep circling back to is worth naming out loud.",
  "Today rewards curiosity more than certainty.",
  "A short walk or break today will clear more than an hour of worrying.",
  "You're not behind — today just asks for a different pace.",
  "The people around you notice your steadiness more than you think.",
  "Today, one honest sentence beats a long explanation.",
  "A little discomfort today is a sign of growth, not failure.",
  "You have permission to do less today and still call it a good day.",
  "Today's small win deserves to be noticed, even if no one else sees it.",
  "The answer you need is probably already something you know.",
  "Today favors finishing over starting something new.",
  "A little humor today will lighten something heavier than expected.",
  "You're allowed to ask for help with the thing you've been carrying alone.",
  "Today, trust is built in small moments, not grand gestures.",
  "Something you let go of today makes room for something better.",
  "The version of you from a year ago would be proud of today's version.",
  "Today, saying less and listening more opens a door.",
  "A plan made in patience today outlasts one made in urgency.",
  "You're exactly on time for whatever today actually needs from you.",
  "Today's quiet moments matter as much as its busy ones.",
  "The thing that feels risky today is more survivable than it seems.",
  "You don't owe anyone an instant answer today.",
  "A little structure early in the day frees up the rest of it.",
  "Today, your calm is more useful to others than your certainty.",
  "Something good is quietly compounding from the effort you've already put in.",
  "Today asks for presence more than performance.",
  "You're allowed to protect today from other people's urgency.",
  "The smallest step you take today still counts as movement.",
  "Today, choosing rest is also choosing progress.",
];

export const messagesRu: readonly string[] = [
  "Сегодня маленькие честные шаги вознаграждаются больше, чем громкие жесты.",
  "То, о чём ты слишком много думаешь, проще, чем кажется прямо сейчас.",
  "Короткая пауза сегодня сэкономит тебе более долгую позже.",
  "Тебе не обязательно всё решить к вечеру.",
  "Хороший сегодняшний день начинается с доброты к себе.",
  "Разговор, который ты откладывал(а), готов случиться раньше, чем думаешь.",
  "Не каждый открытый вопрос нужно закрывать сегодня — пусть некоторые остаются открытыми.",
  "Ты ближе к маленькому прорыву, чем казалось в последние дни.",
  "Сегодня лучше сделать следующий правильный шаг, чем искать идеальный.",
  "Что-то тихо работает в твою пользу, даже если пока не видно.",
  "У тебя больше влияния на сегодняшний день, чем кажется утром.",
  "Немного порядка сегодня ощутится как облегчение, а не ограничение.",
  "То, из-за чего ты волнуешься, окажется меньше, стоит только начать.",
  "Сегодня хороший день, чтобы чуть больше довериться первому инстинкту.",
  "Кому-то рядом пригодится именно то внимание, которое ты умеешь давать.",
  "Немного терпения сегодня предотвратит большее разочарование завтра.",
  "Тебе разрешено сегодня радоваться чему-то без объяснений.",
  "План не обязан быть идеальным — ему нужно просто начаться.",
  "То, что кажется сегодня неудачей, скорее всего просто смена направления.",
  "Сегодня меньше объяснений и больше действий пойдут на пользу.",
  "Немного честности с собой сегодня расчищает больше, чем стоит.",
  "Сегодня тебя просят выбрать устойчивость, а не скорость.",
  "Энергия первого часа обычно задаёт тон всему дню.",
  "То, что ты закончишь сегодня, будет значить больше через неделю, чем кажется сейчас.",
  "Сегодня есть место для одного важного дела, а не для десяти мелких.",
  "Граница, которую ты установишь сегодня, будет неловкой минуту и полезной потом.",
  "Сложную часть ты уже сделал(а) — сегодня дело за тем, чтобы довести до конца.",
  "Чужое мнение о тебе сегодня говорит больше о них, чем о тебе.",
  "Маленькая доброта сегодня стоит немного, а действует дольше, чем ожидаешь.",
  "Сегодня более тихий вариант, вероятно, окажется более мудрым.",
  "Тебе разрешено сегодня передумать насчёт чего-то.",
  "То, к чему ты постоянно возвращаешься мыслями, стоит назвать вслух.",
  "Сегодня любопытство вознаграждается больше, чем уверенность.",
  "Короткая прогулка или перерыв сегодня прояснит больше, чем час тревог.",
  "Ты не отстаёшь — сегодня просто нужен другой темп.",
  "Люди вокруг замечают твою устойчивость больше, чем ты думаешь.",
  "Сегодня одно честное предложение лучше долгого объяснения.",
  "Небольшой дискомфорт сегодня — знак роста, а не провала.",
  "Тебе разрешено сегодня сделать меньше и всё равно назвать день хорошим.",
  "Маленькая победа сегодня заслуживает быть замеченной, даже если никто больше не видит.",
  "Ответ, который тебе нужен, скорее всего, ты уже знаешь.",
  "Сегодня лучше закончить начатое, чем начинать новое.",
  "Немного юмора сегодня облегчит то, что казалось тяжелее, чем есть.",
  "Тебе разрешено попросить о помощи с тем, что ты нёс(ла) в одиночку.",
  "Сегодня доверие строится в маленьких моментах, а не в громких жестах.",
  "То, что ты сегодня отпустишь, освобождает место для лучшего.",
  "Ты собой год назад гордился(лась) бы сегодняшним собой.",
  "Сегодня, говоря меньше и слушая больше, ты откроешь дверь.",
  "План, составленный терпеливо сегодня, переживёт составленный второпях.",
  "Ты как раз вовремя для того, что сегодня действительно нужно.",
  "Тихие моменты сегодня важны так же, как и насыщенные.",
  "То, что кажется рискованным сегодня, пережить легче, чем кажется.",
  "Ты никому не должен(на) мгновенный ответ сегодня.",
  "Немного порядка с утра освобождает остаток дня.",
  "Сегодня твоё спокойствие полезнее для других, чем твоя уверенность.",
  "Что-то хорошее тихо накапливается от уже вложенных усилий.",
  "Сегодня важнее присутствие, чем демонстрация.",
  "Тебе разрешено защищать сегодняшний день от чужой спешки.",
  "Даже самый маленький шаг сегодня всё ещё считается движением.",
  "Сегодня выбрать отдых — тоже выбрать прогресс.",
];

export const luckyMomentsEn: readonly string[] = [
  "Late morning, around 10-11am", "Right after you wake up, before checking your phone",
  "The first quiet moment after lunch", "Golden hour, just before sunset",
  "Whenever you take your first real break", "The moment you finish your first task of the day",
  "Mid-afternoon, when energy usually dips", "Right before you fall asleep tonight",
  "The first conversation you have today", "Whenever you step outside next",
  "The next time you laugh without meaning to", "Early evening, once the day slows down",
  "The moment you stop checking notifications", "Right when you feel like giving up on something small",
  "The next unplanned five minutes you get", "Whenever you make eye contact with a stranger",
  "The second cup of coffee or tea today", "Just after you finally send that message",
  "The quiet ten minutes before a meeting", "Whenever today feels the most ordinary",
];

export const luckyMomentsRu: readonly string[] = [
  "Позднее утро, около 10-11 часов", "Сразу после пробуждения, до проверки телефона",
  "Первая тихая минута после обеда", "Золотой час, перед самым закатом",
  "Момент твоего первого настоящего перерыва", "Момент завершения первого дела дня",
  "Середина дня, когда обычно падает энергия", "Прямо перед тем, как заснуть сегодня",
  "Первый сегодняшний разговор", "Момент, когда выйдешь на улицу в следующий раз",
  "Следующий раз, когда рассмеёшься неожиданно для себя", "Ранний вечер, когда день замедляется",
  "Момент, когда перестанешь проверять уведомления", "Момент, когда захочется бросить что-то маленькое",
  "Ближайшие незапланированные пять минут", "Момент, когда встретишься взглядом с незнакомцем",
  "Вторая чашка кофе или чая сегодня", "Сразу после того, как наконец отправишь то сообщение",
  "Тихие десять минут перед встречей", "Момент, когда день покажется самым обычным",
];
