import type { Question } from "../types";

const P = (en: string, ru: string) => ({ en, ru });

export const classificationQuestions: Question[] = [
  {
    id: 701,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Apple", "Яблоко") },
      { id: "B", text: P("Banana", "Банан") },
      { id: "C", text: P("Carrot", "Морковь") },
      { id: "D", text: P("Orange", "Апельсин") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Apple, banana, and orange are all fruits; carrot is a vegetable.",
      "Яблоко, банан и апельсин — фрукты; морковь — овощ.",
    ),
    weight: 1,
  },
  {
    id: 702,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Guitar", "Гитара") },
      { id: "B", text: P("Violin", "Скрипка") },
      { id: "C", text: P("Piano", "Пианино") },
      { id: "D", text: P("Drum", "Барабан") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Guitar, violin, and piano all produce a musical pitch/melody using strings or keys; a drum is a percussion instrument without a defined melodic pitch.",
      "Гитара, скрипка и пианино издают определённую мелодическую высоту звука с помощью струн или клавиш; барабан — ударный инструмент без определённой мелодической высоты.",
    ),
    weight: 1,
  },
  {
    id: 703,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which number does not belong with the others?", "Какое число лишнее?"),
    options: [
      { id: "A", text: P("4", "4") },
      { id: "B", text: P("9", "9") },
      { id: "C", text: P("16", "16") },
      { id: "D", text: P("18", "18") },
    ],
    correctAnswer: "D",
    explanation: P(
      "4, 9, and 16 are all perfect squares (2², 3², 4²); 18 is not a perfect square.",
      "4, 9 и 16 — точные квадраты (2², 3², 4²); 18 не является точным квадратом.",
    ),
    weight: 1,
  },
  {
    id: 704,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Whale", "Кит") },
      { id: "B", text: P("Dolphin", "Дельфин") },
      { id: "C", text: P("Shark", "Акула") },
      { id: "D", text: P("Seal", "Тюлень") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Whales, dolphins, and seals are mammals that breathe air; a shark is a fish that breathes through gills.",
      "Киты, дельфины и тюлени — млекопитающие, дышащие воздухом; акула — рыба, дышащая жабрами.",
    ),
    weight: 1.5,
  },
  {
    id: 705,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which number does not belong with the others?", "Какое число лишнее?"),
    options: [
      { id: "A", text: P("2", "2") },
      { id: "B", text: P("3", "3") },
      { id: "C", text: P("9", "9") },
      { id: "D", text: P("11", "11") },
    ],
    correctAnswer: "C",
    explanation: P(
      "2, 3, and 11 are all prime numbers; 9 is not prime (3 × 3).",
      "2, 3 и 11 — простые числа; 9 не является простым числом (3 × 3).",
    ),
    weight: 1.5,
  },
  {
    id: 706,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Triangle", "Треугольник") },
      { id: "B", text: P("Square", "Квадрат") },
      { id: "C", text: P("Circle", "Круг") },
      { id: "D", text: P("Pentagon", "Пятиугольник") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Triangle, square, and pentagon are all polygons made of straight-line sides; a circle has no straight sides.",
      "Треугольник, квадрат и пятиугольник — многоугольники с прямыми сторонами; круг не имеет прямых сторон.",
    ),
    weight: 1.5,
  },
  {
    id: 707,
    category: "classification",
    difficulty: "medium",
    prompt: P(
      "Count how many times the letter 'e' appears in this sentence: 'The evening breeze felt gentle.'",
      "Сосчитайте, сколько раз буква «е» встречается в этом предложении: «В деревне тихим вечером девочка напевала весёлые песни.»",
    ),
    options: [
      { id: "A", text: P("8", "9") },
      { id: "B", text: P("9", "10") },
      { id: "C", text: P("10", "11") },
      { id: "D", text: P("11", "12") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Counting carefully letter by letter (case-insensitive) in the sentence yields 9 occurrences of 'e' (this tests sustained visual attention, not vocabulary).",
      "Внимательный подсчёт буквы «е» (без учёта «ё») в предложении даёт 10 вхождений (это задание проверяет устойчивость внимания, а не словарный запас).",
    ),
    weight: 1.5,
  },
  {
    id: 708,
    category: "classification",
    difficulty: "hard",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Democracy", "Демократия") },
      { id: "B", text: P("Monarchy", "Монархия") },
      { id: "C", text: P("Oligarchy", "Олигархия") },
      { id: "D", text: P("Geography", "География") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Democracy, monarchy, and oligarchy are all systems of governance; geography is the study of the Earth's physical features, an unrelated field.",
      "Демократия, монархия и олигархия — системы государственного управления; география — наука о физических особенностях Земли, не связанная с ними область.",
    ),
    weight: 2,
  },
  {
    id: 709,
    category: "classification",
    difficulty: "hard",
    prompt: P(
      "In the string 'XOXXOXOXXOXXXOXO', how many times does the pair 'XO' appear (reading left to right, overlapping allowed)?",
      "В строке «XOXXOXOXXOXXXOXO» сколько раз встречается пара «XO» (читая слева направо, с учётом перекрытий)?",
    ),
    options: [
      { id: "A", text: P("5", "5") },
      { id: "B", text: P("6", "6") },
      { id: "C", text: P("7", "7") },
      { id: "D", text: P("8", "8") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Scanning the string X-O-X-X-O-X-O-X-X-O-X-X-X-O-X-O for the adjacent pair 'XO' finds 6 occurrences, starting at positions 1, 4, 6, 9, 13, and 15 — this tests sustained attention to detail.",
      "Просмотр строки X-О-X-X-О-X-О-X-X-О-X-X-X-О-X-О на предмет соседней пары «XO» даёт 6 совпадений, начинающихся на позициях 1, 4, 6, 9, 13 и 15 — задание проверяет устойчивость внимания к деталям.",
    ),
    weight: 2,
  },
  {
    id: 710,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Novel", "Роман") },
      { id: "B", text: P("Poem", "Стихотворение") },
      { id: "C", text: P("Essay", "Эссе") },
      { id: "D", text: P("Sculpture", "Скульптура") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Novel, poem, and essay are all forms of written literature; sculpture is a visual/physical art form, not a written one.",
      "Роман, стихотворение и эссе — формы письменной литературы; скульптура — визуальная/физическая форма искусства, а не письменная.",
    ),
    weight: 1.5,
  },
  {
    id: 711,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Hammer", "Молоток") },
      { id: "B", text: P("Screwdriver", "Отвёртка") },
      { id: "C", text: P("Wrench", "Гаечный ключ") },
      { id: "D", text: P("Nail", "Гвоздь") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Hammer, screwdriver, and wrench are all tools used to perform work; a nail is a fastener that tools act upon, not a tool itself.",
      "Молоток, отвёртка и гаечный ключ — инструменты для выполнения работы; гвоздь — крепёжный элемент, на который воздействуют инструментом, а не сам инструмент.",
    ),
    weight: 1,
  },
  {
    id: 712,
    category: "classification",
    difficulty: "hard",
    prompt: P(
      "In a grid of symbols, one symbol type is repeated many times with a single instance of a mirrored version hidden among them: '◣◣◣◣◢◣◣◣◣◣◣◣◣'. At which position (counting from 1) is the mirrored symbol '◢'?",
      "В сетке символов один тип повторяется много раз, а среди них спрятан один зеркальный вариант: «◣◣◣◣◢◣◣◣◣◣◣◣◣». На какой позиции (считая с 1) находится зеркальный символ «◢»?",
    ),
    options: [
      { id: "A", text: P("3", "3") },
      { id: "B", text: P("5", "5") },
      { id: "C", text: P("7", "7") },
      { id: "D", text: P("9", "9") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Counting the symbols in order, the mirrored '◢' appears as the 5th symbol in the sequence.",
      "При последовательном подсчёте символов зеркальный «◢» оказывается 5-м символом в ряду.",
    ),
    weight: 2,
  },
  {
    id: 713,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Rose", "Роза") },
      { id: "B", text: P("Tulip", "Тюльпан") },
      { id: "C", text: P("Daisy", "Ромашка") },
      { id: "D", text: P("Oak", "Дуб") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Rose, tulip, and daisy are all flowers; an oak is a tree.",
      "Роза, тюльпан и ромашка — цветы; дуб — дерево.",
    ),
    weight: 1,
  },
  {
    id: 714,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Football", "Футбол") },
      { id: "B", text: P("Basketball", "Баскетбол") },
      { id: "C", text: P("Tennis", "Теннис") },
      { id: "D", text: P("Painting", "Живопись") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Football, basketball, and tennis are all sports; painting is a visual art, not a sport.",
      "Футбол, баскетбол и теннис — виды спорта; живопись — вид искусства, а не спорт.",
    ),
    weight: 1,
  },
  {
    id: 715,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which number does not belong with the others?", "Какое число лишнее?"),
    options: [
      { id: "A", text: P("10", "10") },
      { id: "B", text: P("20", "20") },
      { id: "C", text: P("25", "25") },
      { id: "D", text: P("30", "30") },
    ],
    correctAnswer: "C",
    explanation: P(
      "10, 20, and 30 are all multiples of 10; 25 is not.",
      "10, 20 и 30 — кратные 10; 25 не кратно 10.",
    ),
    weight: 1,
  },
  {
    id: 716,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Rain", "Дождь") },
      { id: "B", text: P("Snow", "Снег") },
      { id: "C", text: P("Hail", "Град") },
      { id: "D", text: P("Fog", "Туман") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Rain, snow, and hail are all forms of precipitation that fall to the ground; fog is suspended moisture in the air, not precipitation.",
      "Дождь, снег и град — виды осадков, выпадающих на землю; туман — влага, взвешенная в воздухе, а не осадки.",
    ),
    weight: 1.5,
  },
  {
    id: 717,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which number does not belong with the others?", "Какое число лишнее?"),
    options: [
      { id: "A", text: P("8", "8") },
      { id: "B", text: P("27", "27") },
      { id: "C", text: P("36", "36") },
      { id: "D", text: P("64", "64") },
    ],
    correctAnswer: "C",
    explanation: P(
      "8, 27, and 64 are all perfect cubes (2³, 3³, 4³); 36 is a perfect square but not a perfect cube.",
      "8, 27 и 64 — точные кубы (2³, 3³, 4³); 36 — точный квадрат, но не куб.",
    ),
    weight: 1.5,
  },
  {
    id: 718,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Novel", "Роман") },
      { id: "B", text: P("Magazine", "Журнал") },
      { id: "C", text: P("Newspaper", "Газета") },
      { id: "D", text: P("Radio", "Радио") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Novel, magazine, and newspaper are all printed reading material; radio is an audio broadcast medium, not something you read.",
      "Роман, журнал и газета — печатные издания для чтения; радио — аудио-медиа, его не читают.",
    ),
    weight: 1.5,
  },
  {
    id: 719,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Ant", "Муравей") },
      { id: "B", text: P("Bee", "Пчела") },
      { id: "C", text: P("Spider", "Паук") },
      { id: "D", text: P("Beetle", "Жук") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Ant, bee, and beetle are all insects with six legs; a spider is an arachnid with eight legs.",
      "Муравей, пчела и жук — насекомые с шестью ногами; паук — паукообразное с восемью ногами.",
    ),
    weight: 1.5,
  },
  {
    id: 720,
    category: "classification",
    difficulty: "hard",
    prompt: P(
      "Count how many times the digit '3' appears in the following list of numbers: 13, 33, 34, 43, 53, 73.",
      "Сосчитайте, сколько раз цифра «3» встречается в следующем списке чисел: 13, 33, 34, 43, 53, 73.",
    ),
    options: [
      { id: "A", text: P("6", "6") },
      { id: "B", text: P("7", "7") },
      { id: "C", text: P("8", "8") },
      { id: "D", text: P("9", "9") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Counting digit by digit: 13(1), 33(2), 34(1), 43(1), 53(1), 73(1) — total 1+2+1+1+1+1 = 7 occurrences of '3'.",
      "Считаем по цифрам: 13(1), 33(2), 34(1), 43(1), 53(1), 73(1) — всего 1+2+1+1+1+1 = 7 вхождений цифры «3».",
    ),
    weight: 2,
  },
  {
    id: 721,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Happy", "Счастливый") },
      { id: "B", text: P("Joyful", "Радостный") },
      { id: "C", text: P("Cheerful", "Весёлый") },
      { id: "D", text: P("Angry", "Сердитый") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Happy, joyful, and cheerful all describe positive emotional states; angry describes a negative emotional state.",
      "Счастливый, радостный и весёлый описывают положительные эмоции; сердитый описывает отрицательную эмоцию.",
    ),
    weight: 1,
  },
  {
    id: 722,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Continent", "Континент") },
      { id: "B", text: P("Country", "Страна") },
      { id: "C", text: P("City", "Город") },
      { id: "D", text: P("River", "Река") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Continent, country, and city are all political/geographic administrative or population units of decreasing scale; a river is a natural landform, not an administrative unit.",
      "Континент, страна и город — административные или населённые единицы убывающего масштаба; река — природный географический объект, а не административная единица.",
    ),
    weight: 1.5,
  },
  {
    id: 723,
    category: "classification",
    difficulty: "hard",
    prompt: P(
      "In the string 'AABAABAABBAAB', how many times does the substring 'AAB' appear (reading left to right, overlapping allowed)?",
      "В строке «AABAABAABBAAB» сколько раз встречается подстрока «AAB» (слева направо, с учётом перекрытий)?",
    ),
    options: [
      { id: "A", text: P("3", "3") },
      { id: "B", text: P("4", "4") },
      { id: "C", text: P("5", "5") },
      { id: "D", text: P("6", "6") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Scanning positions 1-13 of A-A-B-A-A-B-A-A-B-B-A-A-B for 'AAB': matches start at positions 1, 4, 7, and 11 — 4 occurrences total.",
      "Просматривая позиции 1-13 строки A-A-B-A-A-B-A-A-B-B-A-A-B на предмет «AAB»: совпадения начинаются на позициях 1, 4, 7 и 11 — всего 4 совпадения.",
    ),
    weight: 2,
  },
  {
    id: 724,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Trumpet", "Труба") },
      { id: "B", text: P("Flute", "Флейта") },
      { id: "C", text: P("Saxophone", "Саксофон") },
      { id: "D", text: P("Cello", "Виолончель") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Trumpet, flute, and saxophone are all wind instruments played by blowing air; a cello is a string instrument played with a bow.",
      "Труба, флейта и саксофон — духовые инструменты, звук извлекается вдуванием воздуха; виолончель — струнный инструмент, звук извлекается смычком.",
    ),
    weight: 1.5,
  },
  {
    id: 725,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which number does not belong with the others?", "Какое число лишнее?"),
    options: [
      { id: "A", text: P("1/2", "1/2") },
      { id: "B", text: P("2/4", "2/4") },
      { id: "C", text: P("3/6", "3/6") },
      { id: "D", text: P("2/3", "2/3") },
    ],
    correctAnswer: "D",
    explanation: P(
      "1/2, 2/4, and 3/6 are all equivalent fractions equal to one half; 2/3 is a different value.",
      "1/2, 2/4 и 3/6 — равнозначные дроби, равные одной второй; 2/3 — другое значение.",
    ),
    weight: 1,
  },
  {
    id: 726,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Kilogram", "Килограмм") },
      { id: "B", text: P("Pound", "Фунт") },
      { id: "C", text: P("Ounce", "Унция") },
      { id: "D", text: P("Meter", "Метр") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Kilogram, pound, and ounce are all units of weight/mass; a meter is a unit of length.",
      "Килограмм, фунт и унция — единицы веса/массы; метр — единица длины.",
    ),
    weight: 1.5,
  },
  {
    id: 727,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Volcano", "Вулкан") },
      { id: "B", text: P("Earthquake", "Землетрясение") },
      { id: "C", text: P("Hurricane", "Ураган") },
      { id: "D", text: P("Bridge", "Мост") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Volcano, earthquake, and hurricane are all natural phenomena/disasters; a bridge is a human-made structure.",
      "Вулкан, землетрясение и ураган — природные явления/катастрофы; мост — сооружение, созданное человеком.",
    ),
    weight: 1.5,
  },
  {
    id: 728,
    category: "classification",
    difficulty: "hard",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Inflation", "Инфляция") },
      { id: "B", text: P("Recession", "Рецессия") },
      { id: "C", text: P("Surplus", "Излишек") },
      { id: "D", text: P("Latitude", "Широта") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Inflation, recession, and surplus are all economic terms; latitude is a geographic coordinate term, unrelated to economics.",
      "Инфляция, рецессия и излишек — экономические термины; широта — географический термин координат, не связанный с экономикой.",
    ),
    weight: 2,
  },
  {
    id: 729,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Cup", "Чашка") },
      { id: "B", text: P("Glass", "Стакан") },
      { id: "C", text: P("Mug", "Кружка") },
      { id: "D", text: P("Plate", "Тарелка") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Cup, glass, and mug are all vessels primarily for drinking; a plate is for holding food, not drinking.",
      "Чашка, стакан и кружка — сосуды в первую очередь для питья; тарелка предназначена для еды, а не для питья.",
    ),
    weight: 1,
  },
  {
    id: 730,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which number does not belong with the others?", "Какое число лишнее?"),
    options: [
      { id: "A", text: P("15", "15") },
      { id: "B", text: P("21", "21") },
      { id: "C", text: P("28", "28") },
      { id: "D", text: P("30", "30") },
    ],
    correctAnswer: "D",
    explanation: P(
      "15, 21, and 28 are all triangular numbers (sums of consecutive integers starting from 1); 30 is not a triangular number.",
      "15, 21 и 28 — треугольные числа (суммы последовательных целых чисел, начиная с 1); 30 не является треугольным числом.",
    ),
    weight: 1.5,
  },
  {
    id: 731,
    category: "classification",
    difficulty: "hard",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Adagio", "Адажио") },
      { id: "B", text: P("Allegro", "Аллегро") },
      { id: "C", text: P("Largo", "Ларго") },
      { id: "D", text: P("Crescendo", "Крещендо") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Adagio, Allegro, and Largo are all musical tempo markings (indicating speed); Crescendo indicates a gradual change in volume, not speed.",
      "Адажио, Аллегро и Ларго — обозначения темпа в музыке (скорости исполнения); Крещендо обозначает постепенное изменение громкости, а не темпа.",
    ),
    weight: 2,
  },
  {
    id: 732,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Oxygen", "Кислород") },
      { id: "B", text: P("Nitrogen", "Азот") },
      { id: "C", text: P("Helium", "Гелий") },
      { id: "D", text: P("Water", "Вода") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Oxygen, nitrogen, and helium are all elements that exist as gases at room temperature; water is a compound, not a single element.",
      "Кислород, азот и гелий — химические элементы, существующие как газы при комнатной температуре; вода — соединение, а не отдельный элемент.",
    ),
    weight: 1.5,
  },
  {
    id: 733,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Spring", "Весна") },
      { id: "B", text: P("Summer", "Лето") },
      { id: "C", text: P("Autumn", "Осень") },
      { id: "D", text: P("Monday", "Понедельник") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Spring, summer, and autumn are all seasons of the year; Monday is a day of the week, a different unit of time.",
      "Весна, лето и осень — времена года; понедельник — день недели, другая единица измерения времени.",
    ),
    weight: 1,
  },
  {
    id: 734,
    category: "classification",
    difficulty: "hard",
    prompt: P(
      "In the sequence of symbols '★★☆★★★☆★★☆★★', how many times does the pair '★☆' appear (reading left to right)?",
      "В последовательности символов «★★☆★★★☆★★☆★★» сколько раз встречается пара «★☆» (слева направо)?",
    ),
    options: [
      { id: "A", text: P("2", "2") },
      { id: "B", text: P("3", "3") },
      { id: "C", text: P("4", "4") },
      { id: "D", text: P("5", "5") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Reading the 13 symbols in order (★★☆★★★☆★★☆★★), the adjacent pair '★☆' occurs at positions 2-3, 6-7, and 9-10 — 3 occurrences.",
      "Читая все 13 символов по порядку (★★☆★★★☆★★☆★★), соседняя пара «★☆» встречается на позициях 2-3, 6-7 и 9-10 — 3 совпадения.",
    ),
    weight: 2,
  },
  {
    id: 735,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Copper", "Медь") },
      { id: "B", text: P("Iron", "Железо") },
      { id: "C", text: P("Aluminum", "Алюминий") },
      { id: "D", text: P("Diamond", "Алмаз") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Copper, iron, and aluminum are all metals; a diamond is a crystalline form of carbon, not a metal.",
      "Медь, железо и алюминий — металлы; алмаз — кристаллическая форма углерода, а не металл.",
    ),
    weight: 1.5,
  },
  {
    id: 736,
    category: "classification",
    difficulty: "easy",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Rectangle", "Прямоугольник") },
      { id: "B", text: P("Sphere", "Сфера") },
      { id: "C", text: P("Cube", "Куб") },
      { id: "D", text: P("Cylinder", "Цилиндр") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Sphere, cube, and cylinder are all three-dimensional solid shapes; a rectangle is a two-dimensional flat shape.",
      "Сфера, куб и цилиндр — трёхмерные объёмные фигуры; прямоугольник — двумерная плоская фигура.",
    ),
    weight: 1,
  },
  {
    id: 737,
    category: "classification",
    difficulty: "medium",
    prompt: P("Which word does not belong with the others?", "Какое слово лишнее?"),
    options: [
      { id: "A", text: P("Bacteria", "Бактерии") },
      { id: "B", text: P("Virus", "Вирус") },
      { id: "C", text: P("Fungus", "Гриб") },
      { id: "D", text: P("Vitamin", "Витамин") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Bacteria, virus, and fungus are all types of biological organisms or infectious agents; a vitamin is a nutrient compound, not a living organism.",
      "Бактерии, вирус и гриб — виды биологических организмов или возбудителей инфекций; витамин — питательное соединение, а не живой организм.",
    ),
    weight: 1.5,
  },
  {
    id: 738,
    category: "classification",
    difficulty: "hard",
    prompt: P("Which number does not belong with the others?", "Какое число лишнее?"),
    options: [
      { id: "A", text: P("6", "6") },
      { id: "B", text: P("28", "28") },
      { id: "C", text: P("496", "496") },
      { id: "D", text: P("500", "500") },
    ],
    correctAnswer: "D",
    explanation: P(
      "6, 28, and 496 are all perfect numbers (equal to the sum of their proper divisors: 1+2+3=6, 1+2+4+7+14=28); 500 is not a perfect number.",
      "6, 28 и 496 — совершенные числа (равны сумме своих собственных делителей: 1+2+3=6, 1+2+4+7+14=28); 500 не является совершенным числом.",
    ),
    weight: 2,
  },
];
