import type { Question } from "../types";

const P = (en: string, ru: string) => ({ en, ru });

export const logicalQuestions: Question[] = [
  {
    id: 501,
    category: "logical",
    difficulty: "easy",
    prompt: P(
      "All roses are flowers. Some flowers fade quickly. Which conclusion must be true?",
      "Все розы — это цветы. Некоторые цветы быстро увядают. Какой вывод обязательно верен?",
    ),
    options: [
      { id: "A", text: P("All roses fade quickly.", "Все розы быстро увядают.") },
      { id: "B", text: P("Some roses are flowers.", "Некоторые розы — цветы.") },
      { id: "C", text: P("No roses fade quickly.", "Ни одна роза не увядает быстро.") },
      { id: "D", text: P("All flowers are roses.", "Все цветы — розы.") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Since all roses are flowers, it necessarily follows that some (in fact all) roses are flowers. The other options overreach the given information.",
      "Так как все розы — цветы, обязательно следует, что некоторые (и даже все) розы являются цветами. Остальные варианты выходят за рамки данных.",
    ),
    weight: 1,
  },
  {
    id: 502,
    category: "logical",
    difficulty: "easy",
    prompt: P(
      "If it rains, the ground gets wet. The ground is not wet. What can you conclude?",
      "Если идёт дождь, земля становится мокрой. Земля не мокрая. Какой вывод можно сделать?",
    ),
    options: [
      { id: "A", text: P("It rained.", "Шёл дождь.") },
      { id: "B", text: P("It did not rain.", "Дождя не было.") },
      { id: "C", text: P("It might have rained.", "Возможно, шёл дождь.") },
      { id: "D", text: P("The ground is wet.", "Земля мокрая.") },
    ],
    correctAnswer: "B",
    explanation: P(
      "This is a valid contrapositive (modus tollens): if rain implies wet ground, and the ground is not wet, then it did not rain.",
      "Это правильный вывод методом modus tollens: если дождь влечёт мокрую землю, а земля не мокрая, значит дождя не было.",
    ),
    weight: 1,
  },
  {
    id: 503,
    category: "logical",
    difficulty: "easy",
    prompt: P(
      "Anna is taller than Beth. Beth is taller than Carla. Who is the shortest?",
      "Анна выше Бет. Бет выше Карлы. Кто самая низкая?",
    ),
    options: [
      { id: "A", text: P("Anna", "Анна") },
      { id: "B", text: P("Beth", "Бет") },
      { id: "C", text: P("Carla", "Карла") },
      { id: "D", text: P("Cannot be determined", "Невозможно определить") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Anna > Beth > Carla in height, so Carla is the shortest of the three.",
      "По росту: Анна > Бет > Карла, значит Карла — самая низкая из троих.",
    ),
    weight: 1,
  },
  {
    id: 504,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "No fish can fly. All salmon are fish. Which conclusion must be true?",
      "Ни одна рыба не умеет летать. Весь лосось — это рыба. Какой вывод обязательно верен?",
    ),
    options: [
      { id: "A", text: P("No salmon can fly.", "Ни один лосось не умеет летать.") },
      { id: "B", text: P("Some salmon can fly.", "Некоторый лосось умеет летать.") },
      { id: "C", text: P("All flying things are fish.", "Всё летающее — рыба.") },
      { id: "D", text: P("Some fish are not salmon.", "Некоторые рыбы — не лосось.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since all salmon are fish, and no fish can fly, it follows that no salmon can fly.",
      "Так как весь лосось — рыба, а ни одна рыба не летает, следует, что ни один лосось не летает.",
    ),
    weight: 1.5,
  },
  {
    id: 505,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "Of five friends, David runs faster than Elena. Elena runs faster than Frank. Frank runs faster than Grace. Grace runs faster than Henry. Who runs the second fastest?",
      "Из пяти друзей Давид бегает быстрее Елены. Елена бегает быстрее Франка. Франк бегает быстрее Грейс. Грейс бегает быстрее Генри. Кто бегает второй по скорости?",
    ),
    options: [
      { id: "A", text: P("David", "Давид") },
      { id: "B", text: P("Elena", "Елена") },
      { id: "C", text: P("Frank", "Франк") },
      { id: "D", text: P("Grace", "Грейс") },
    ],
    correctAnswer: "B",
    explanation: P(
      "The order from fastest to slowest is: David, Elena, Frank, Grace, Henry. Elena is second.",
      "Порядок от самого быстрого к самому медленному: Давид, Елена, Франк, Грейс, Генри. Елена — вторая.",
    ),
    weight: 1.5,
  },
  {
    id: 506,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "Every member of the chess club also plays checkers. Maria plays checkers. Can we conclude Maria is a member of the chess club?",
      "Каждый член шахматного клуба также играет в шашки. Мария играет в шашки. Можно ли сделать вывод, что Мария — член шахматного клуба?",
    ),
    options: [
      { id: "A", text: P("Yes, it must be true.", "Да, это обязательно так.") },
      { id: "B", text: P("No, this does not follow.", "Нет, это не следует из условия.") },
      { id: "C", text: P("Yes, but only on weekends.", "Да, но только по выходным.") },
      { id: "D", text: P("No, because checkers players cannot play chess.", "Нет, потому что игроки в шашки не могут играть в шахматы.") },
    ],
    correctAnswer: "B",
    explanation: P(
      "The statement only guarantees that chess club members play checkers — not the reverse. Maria playing checkers does not mean she is in the chess club (affirming the consequent).",
      "Утверждение гарантирует только то, что члены шахматного клуба играют в шашки, но не наоборот. То, что Мария играет в шашки, не означает, что она в шахматном клубе (ошибка утверждения следствия).",
    ),
    weight: 1.5,
  },
  {
    id: 507,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "In a certain code, if 'all bloops are razzies' and 'no razzies are lazzies' are both true, which must also be true?",
      "В определённом коде верны утверждения «все блупы — это рэззи» и «ни один рэззи не является лэззи». Что из этого обязательно верно?",
    ),
    options: [
      { id: "A", text: P("No bloops are lazzies.", "Ни один блуп не является лэззи.") },
      { id: "B", text: P("All lazzies are bloops.", "Все лэззи — это блупы.") },
      { id: "C", text: P("Some bloops are lazzies.", "Некоторые блупы являются лэззи.") },
      { id: "D", text: P("All razzies are bloops.", "Все рэззи — это блупы.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "All bloops are razzies, and no razzies are lazzies, so bloops (being entirely within razzies) cannot be lazzies either. No bloops are lazzies.",
      "Все блупы — рэззи, а ни один рэззи не является лэззи, значит блупы (полностью входящие в рэззи) тоже не могут быть лэззи. Ни один блуп не является лэззи.",
    ),
    weight: 1.5,
  },
  {
    id: 508,
    category: "logical",
    difficulty: "hard",
    prompt: P(
      "Four people — Kim, Leo, Mona, and Nick — sit in a row. Kim is not at either end. Leo sits immediately to the left of Kim. Nick is at the right end. What is the order from left to right?",
      "Четыре человека — Ким, Лео, Мона и Ник — сидят в ряд. Ким не сидит с краю. Лео сидит непосредственно слева от Ким. Ник сидит с правого края. Каков порядок слева направо?",
    ),
    options: [
      { id: "A", text: P("Mona, Leo, Kim, Nick", "Мона, Лео, Ким, Ник") },
      { id: "B", text: P("Leo, Kim, Mona, Nick", "Лео, Ким, Мона, Ник") },
      { id: "C", text: P("Leo, Mona, Kim, Nick", "Лео, Мона, Ким, Ник") },
      { id: "D", text: P("Mona, Kim, Leo, Nick", "Мона, Ким, Лео, Ник") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Nick is at the right end (position 4). Kim is not at either end, so Kim is in position 2 or 3. Leo is immediately left of Kim. If Kim is in position 3, Leo is in position 2, leaving Mona for position 1: Mona, Leo, Kim, Nick — consistent with all clues.",
      "Ник — на позиции 4 (правый край). Ким не с краю, значит на позиции 2 или 3. Лео — сразу слева от Ким. Если Ким на позиции 3, то Лео на позиции 2, а Мона занимает позицию 1: Мона, Лео, Ким, Ник — соответствует всем условиям.",
    ),
    weight: 2,
  },
  {
    id: 509,
    category: "logical",
    difficulty: "hard",
    prompt: P(
      "Three boxes are labeled 'Apples', 'Oranges', and 'Mixed'. Every label is wrong. You may draw one fruit from one box to figure out the true contents of all three. Which box should you draw from?",
      "На трёх коробках написано «Яблоки», «Апельсины» и «Смесь». Все подписи неверны. Вы можете достать один фрукт из одной коробки, чтобы определить истинное содержимое всех трёх. Из какой коробки нужно достать?",
    ),
    options: [
      { id: "A", text: P("The box labeled 'Apples'", "Коробка с подписью «Яблоки»") },
      { id: "B", text: P("The box labeled 'Oranges'", "Коробка с подписью «Апельсины»") },
      { id: "C", text: P("The box labeled 'Mixed'", "Коробка с подписью «Смесь»") },
      { id: "D", text: P("It doesn't matter which box.", "Не имеет значения, какую коробку выбрать.") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Since every label is wrong, the box labeled 'Mixed' cannot actually be mixed — it must be all apples or all oranges. Drawing one fruit from it reveals its true, single-fruit content, which then forces the other two labels (since none can match their own label) to be deducible.",
      "Так как все подписи неверны, коробка с подписью «Смесь» на самом деле не смешанная — в ней только яблоки или только апельсины. Достав один фрукт оттуда, вы узнаёте её истинное содержимое, а затем можно логически вывести содержимое двух других коробок.",
    ),
    weight: 2,
  },
  {
    id: 510,
    category: "logical",
    difficulty: "hard",
    prompt: P(
      "If some Zorbs are Blips, and all Blips are Cronks, which statement is guaranteed to be true?",
      "Если некоторые Зорбы — это Блипы, а все Блипы — это Кронки, какое утверждение гарантированно верно?",
    ),
    options: [
      { id: "A", text: P("Some Zorbs are Cronks.", "Некоторые Зорбы — это Кронки.") },
      { id: "B", text: P("All Zorbs are Cronks.", "Все Зорбы — это Кронки.") },
      { id: "C", text: P("No Zorbs are Cronks.", "Ни один Зорб не является Кронком.") },
      { id: "D", text: P("All Cronks are Zorbs.", "Все Кронки — это Зорбы.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Some Zorbs are Blips, and every Blip is a Cronk, so those same Zorbs (that are Blips) are also Cronks. This guarantees at least some Zorbs are Cronks — but not necessarily all.",
      "Некоторые Зорбы — Блипы, а каждый Блип — Кронк, значит эти же Зорбы (являющиеся Блипами) — тоже Кронки. Это гарантирует, что хотя бы некоторые Зорбы — Кронки, но не обязательно все.",
    ),
    weight: 2,
  },
  {
    id: 511,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "A statement says: 'If the alarm sounds, then either the door is open or a window is broken.' The alarm sounded, and the door was closed. What must be true?",
      "Утверждение гласит: «Если сработала сигнализация, то либо дверь открыта, либо окно разбито». Сигнализация сработала, а дверь была закрыта. Что должно быть верно?",
    ),
    options: [
      { id: "A", text: P("A window is broken.", "Окно разбито.") },
      { id: "B", text: P("The door is open.", "Дверь открыта.") },
      { id: "C", text: P("Nothing can be concluded.", "Нельзя сделать никакого вывода.") },
      { id: "D", text: P("The alarm is broken.", "Сигнализация неисправна.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since the alarm sounded, at least one of 'door open' or 'window broken' must be true. The door was closed, so by elimination a window must be broken.",
      "Так как сигнализация сработала, верно хотя бы одно из условий: «дверь открыта» или «окно разбито». Дверь была закрыта, значит методом исключения окно разбито.",
    ),
    weight: 1.5,
  },
  {
    id: 512,
    category: "logical",
    difficulty: "easy",
    prompt: P(
      "All squares are rectangles. This shape is not a rectangle. What can you conclude about this shape?",
      "Все квадраты — прямоугольники. Эта фигура — не прямоугольник. Что можно сказать об этой фигуре?",
    ),
    options: [
      { id: "A", text: P("It is not a square.", "Это не квадрат.") },
      { id: "B", text: P("It is a square.", "Это квадрат.") },
      { id: "C", text: P("It might be a square.", "Возможно, это квадрат.") },
      { id: "D", text: P("It is a triangle.", "Это треугольник.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since every square is a rectangle, anything that is not a rectangle cannot be a square (contrapositive).",
      "Так как каждый квадрат — прямоугольник, всё, что не является прямоугольником, не может быть квадратом (метод от противного).",
    ),
    weight: 1,
  },
  {
    id: 513,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "Peter always tells the truth. Peter says, 'My sister is older than me.' If Peter is 30, which must be true?",
      "Пётр всегда говорит правду. Пётр говорит: «Моя сестра старше меня». Если Петру 30, что обязательно верно?",
    ),
    options: [
      { id: "A", text: P("His sister is older than 30.", "Его сестра старше 30 лет.") },
      { id: "B", text: P("His sister is younger than 30.", "Его сестра младше 30 лет.") },
      { id: "C", text: P("His sister is exactly 30.", "Его сестре ровно 30 лет.") },
      { id: "D", text: P("Peter does not have a sister.", "У Петра нет сестры.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since Peter always tells the truth and states his sister is older than him, and he is 30, his sister must be older than 30.",
      "Так как Пётр всегда говорит правду и утверждает, что сестра старше него, а ему 30, значит его сестре больше 30 лет.",
    ),
    weight: 1.5,
  },
  {
    id: 514,
    category: "logical",
    difficulty: "easy",
    prompt: P(
      "Sam is older than Tim. Tim is older than Uma. Who is the oldest of the three?",
      "Сэм старше Тима. Тим старше Умы. Кто из троих самый старший?",
    ),
    options: [
      { id: "A", text: P("Sam", "Сэм") },
      { id: "B", text: P("Tim", "Тим") },
      { id: "C", text: P("Uma", "Ума") },
      { id: "D", text: P("Cannot be determined", "Невозможно определить") },
    ],
    correctAnswer: "A",
    explanation: P(
      "By age: Sam > Tim > Uma, so Sam is the oldest.",
      "По возрасту: Сэм > Тим > Ума, значит Сэм — самый старший.",
    ),
    weight: 1,
  },
  {
    id: 515,
    category: "logical",
    difficulty: "easy",
    prompt: P(
      "If the traffic light is red, cars must stop. The light is red. What must happen?",
      "Если светофор горит красным, машины должны остановиться. Светофор горит красным. Что должно произойти?",
    ),
    options: [
      { id: "A", text: P("Cars must stop.", "Машины должны остановиться.") },
      { id: "B", text: P("Cars may proceed.", "Машины могут проехать.") },
      { id: "C", text: P("The light will change soon.", "Светофор скоро переключится.") },
      { id: "D", text: P("Nothing can be concluded.", "Нельзя сделать никакого вывода.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "This is a direct application of modus ponens: the condition (red light) is met, so its consequence (cars must stop) follows.",
      "Это прямое применение правила modus ponens: условие (красный свет) выполнено, значит следует его следствие (машины должны остановиться).",
    ),
    weight: 1,
  },
  {
    id: 516,
    category: "logical",
    difficulty: "easy",
    prompt: P(
      "All engineers at the firm can code. Lucy cannot code. What can we conclude about Lucy?",
      "Все инженеры в фирме умеют программировать. Люси не умеет программировать. Что можно сказать о Люси?",
    ),
    options: [
      { id: "A", text: P("Lucy is not an engineer at the firm.", "Люси не инженер в этой фирме.") },
      { id: "B", text: P("Lucy is an engineer at the firm.", "Люси — инженер в этой фирме.") },
      { id: "C", text: P("Lucy might be an engineer.", "Люси может быть инженером.") },
      { id: "D", text: P("All engineers cannot code.", "Все инженеры не умеют программировать.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since all engineers can code, and Lucy cannot code, Lucy cannot be an engineer at the firm (contrapositive).",
      "Так как все инженеры умеют программировать, а Люси не умеет, она не может быть инженером в этой фирме (метод от противного).",
    ),
    weight: 1,
  },
  {
    id: 517,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "If an exam is hard, fewer than half the students pass. More than half the students passed this exam. What can you conclude?",
      "Если экзамен трудный, менее половины студентов его сдают. На этом экзамене сдали более половины студентов. Какой вывод можно сделать?",
    ),
    options: [
      { id: "A", text: P("The exam was not hard.", "Экзамен был не трудным.") },
      { id: "B", text: P("The exam was hard.", "Экзамен был трудным.") },
      { id: "C", text: P("The exam might have been hard.", "Экзамен, возможно, был трудным.") },
      { id: "D", text: P("Nothing can be concluded.", "Нельзя сделать никакого вывода.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "This is modus tollens: hard exam implies fewer than half pass; more than half passed (the opposite), so the exam was not hard.",
      "Это правило modus tollens: трудный экзамен подразумевает, что сдаёт менее половины; сдало более половины (противоположное), значит экзамен не был трудным.",
    ),
    weight: 1.5,
  },
  {
    id: 518,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "Four boxes are weighed. Box P is heavier than Box Q. Box Q is heavier than Box R. Box R is heavier than Box S. Which box is the lightest?",
      "Взвесили четыре коробки. Коробка П тяжелее коробки К. Коробка К тяжелее коробки Р. Коробка Р тяжелее коробки С. Какая коробка самая лёгкая?",
    ),
    options: [
      { id: "A", text: P("Box P", "Коробка П") },
      { id: "B", text: P("Box Q", "Коробка К") },
      { id: "C", text: P("Box R", "Коробка Р") },
      { id: "D", text: P("Box S", "Коробка С") },
    ],
    correctAnswer: "D",
    explanation: P(
      "The order from heaviest to lightest is P, Q, R, S. Box S is the lightest.",
      "Порядок от самой тяжёлой к самой лёгкой: П, К, Р, С. Коробка С — самая лёгкая.",
    ),
    weight: 1.5,
  },
  {
    id: 519,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "The company will either expand abroad or hire more local staff. It has not hired more local staff. What follows?",
      "Компания либо расширится за рубежом, либо наймёт больше местного персонала. Она не наняла больше местного персонала. Что из этого следует?",
    ),
    options: [
      { id: "A", text: P("The company will expand abroad.", "Компания расширится за рубежом.") },
      { id: "B", text: P("The company will not expand abroad.", "Компания не будет расширяться за рубежом.") },
      { id: "C", text: P("The company will do neither.", "Компания не сделает ни того, ни другого.") },
      { id: "D", text: P("Nothing can be concluded.", "Нельзя сделать никакого вывода.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "This is a disjunctive syllogism: given 'A or B' and 'not B', it follows that A must be true — the company will expand abroad.",
      "Это разделительный силлогизм: из «А или Б» и «не Б» следует, что верно А — компания расширится за рубежом.",
    ),
    weight: 1.5,
  },
  {
    id: 520,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "All penguins are birds. Some birds cannot fly. Can we conclude that some penguins cannot fly?",
      "Все пингвины — птицы. Некоторые птицы не умеют летать. Можно ли сделать вывод, что некоторые пингвины не умеют летать?",
    ),
    options: [
      { id: "A", text: P("No, this does not necessarily follow.", "Нет, это не следует обязательно.") },
      { id: "B", text: P("Yes, it must be true.", "Да, это обязательно так.") },
      { id: "C", text: P("Yes, but only in winter.", "Да, но только зимой.") },
      { id: "D", text: P("No penguins are birds.", "Ни один пингвин не является птицей.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "The flightless birds mentioned are not guaranteed to include penguins — they could all be some other kind of bird. The conclusion does not necessarily follow from the premises.",
      "Нелетающие птицы, о которых идёт речь, не обязательно включают пингвинов — это могут быть птицы другого вида. Вывод не следует обязательно из условий.",
    ),
    weight: 1.5,
  },
  {
    id: 521,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "Alex always lies. Alex says, 'I have more than 10 books.' What can we conclude about how many books Alex has?",
      "Алекс всегда лжёт. Алекс говорит: «У меня больше 10 книг». Что можно сказать о количестве книг у Алекса?",
    ),
    options: [
      { id: "A", text: P("Alex has 10 or fewer books.", "У Алекса 10 книг или меньше.") },
      { id: "B", text: P("Alex has more than 10 books.", "У Алекса больше 10 книг.") },
      { id: "C", text: P("Alex has exactly 10 books.", "У Алекса ровно 10 книг.") },
      { id: "D", text: P("Alex has no books.", "У Алекса нет книг.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since Alex always lies, the statement 'more than 10 books' must be false, meaning Alex has 10 or fewer books.",
      "Так как Алекс всегда лжёт, утверждение «больше 10 книг» должно быть ложным, значит у Алекса 10 книг или меньше.",
    ),
    weight: 1.5,
  },
  {
    id: 522,
    category: "logical",
    difficulty: "hard",
    prompt: P(
      "A says: 'B is a liar.' B says: 'A and I are both truth-tellers.' Each person either always tells the truth or always lies. Who is telling the truth?",
      "А говорит: «Б — лжец». Б говорит: «Мы с А оба говорим правду». Каждый либо всегда говорит правду, либо всегда лжёт. Кто говорит правду?",
    ),
    options: [
      { id: "A", text: P("A tells the truth, B lies.", "А говорит правду, Б лжёт.") },
      { id: "B", text: P("B tells the truth, A lies.", "Б говорит правду, А лжёт.") },
      { id: "C", text: P("Both tell the truth.", "Оба говорят правду.") },
      { id: "D", text: P("Both lie.", "Оба лгут.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "If B told the truth, then A would also be a truth-teller, so A's claim 'B is a liar' would be true — contradicting B being truthful. So B must be lying, which is consistent with A's claim being true. A tells the truth, B lies.",
      "Если бы Б говорил правду, то А тоже был бы правдивым, и тогда утверждение А «Б — лжец» было бы истинным — противоречие с тем, что Б говорит правду. Значит, Б лжёт, что согласуется с истинностью утверждения А. А говорит правду, Б лжёт.",
    ),
    weight: 2,
  },
  {
    id: 523,
    category: "logical",
    difficulty: "hard",
    prompt: P(
      "Five people — Vera, Wade, Xena, Yuri, and Zack — sit in a row of five seats. Vera sits at one end. Wade sits immediately next to Vera. Xena sits exactly in the middle seat. Zack sits at the other end from Vera. Yuri sits between Xena and Zack. What is the seating order from Vera's end to Zack's end?",
      "Пять человек — Вера, Вадим, Ксения, Юрий и Захар — сидят в ряду из пяти мест. Вера сидит на одном краю. Вадим сидит рядом с Верой. Ксения сидит ровно в середине. Захар сидит на другом краю от Веры. Юрий сидит между Ксенией и Захаром. Каков порядок мест от края Веры до края Захара?",
    ),
    options: [
      { id: "A", text: P("Vera, Wade, Xena, Yuri, Zack", "Вера, Вадим, Ксения, Юрий, Захар") },
      { id: "B", text: P("Vera, Xena, Wade, Yuri, Zack", "Вера, Ксения, Вадим, Юрий, Захар") },
      { id: "C", text: P("Vera, Wade, Yuri, Xena, Zack", "Вера, Вадим, Юрий, Ксения, Захар") },
      { id: "D", text: P("Vera, Yuri, Xena, Wade, Zack", "Вера, Юрий, Ксения, Вадим, Захар") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Vera is at position 1, Zack at position 5. Wade sits immediately next to Vera, so Wade is at position 2. Xena is in the exact middle, position 3. Yuri is between Xena and Zack, so Yuri is at position 4. Order: Vera, Wade, Xena, Yuri, Zack.",
      "Вера на позиции 1, Захар на позиции 5. Вадим сидит рядом с Верой, значит он на позиции 2. Ксения — ровно в середине, позиция 3. Юрий между Ксенией и Захаром, значит он на позиции 4. Порядок: Вера, Вадим, Ксения, Юрий, Захар.",
    ),
    weight: 2,
  },
  {
    id: 524,
    category: "logical",
    difficulty: "easy",
    prompt: P(
      "Being a mammal is necessary for being a dog. This object is not a mammal. Could it be a dog?",
      "Быть млекопитающим — необходимое условие для того, чтобы быть собакой. Этот объект — не млекопитающее. Может ли он быть собакой?",
    ),
    options: [
      { id: "A", text: P("No, it cannot be a dog.", "Нет, он не может быть собакой.") },
      { id: "B", text: P("Yes, it could be a dog.", "Да, он может быть собакой.") },
      { id: "C", text: P("Yes, it is definitely a dog.", "Да, это точно собака.") },
      { id: "D", text: P("It is definitely a mammal.", "Это точно млекопитающее.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "If being a mammal is required to be a dog, then anything that is not a mammal cannot be a dog.",
      "Если быть млекопитающим необходимо, чтобы быть собакой, то всё, что не является млекопитающим, не может быть собакой.",
    ),
    weight: 1,
  },
  {
    id: 525,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "If Maria studies, she passes her class. Maria did not pass her class. What can we conclude about her studying?",
      "Если Мария учится, она сдаёт свой предмет. Мария не сдала предмет. Что можно сказать о том, училась ли она?",
    ),
    options: [
      { id: "A", text: P("Maria did not study.", "Мария не училась.") },
      { id: "B", text: P("Maria studied.", "Мария училась.") },
      { id: "C", text: P("Maria might have studied.", "Возможно, Мария училась.") },
      { id: "D", text: P("Maria passed her class.", "Мария сдала предмет.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "This is modus tollens: studying implies passing; she did not pass, so she did not study.",
      "Это modus tollens: учёба подразумевает сдачу предмета; она его не сдала, значит она не училась.",
    ),
    weight: 1.5,
  },
  {
    id: 526,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "Three cards — red, blue, and green — lie face down in a row in some order. Clue 1: the red card is not leftmost. Clue 2: the blue card is immediately to the right of the green card. What is the order from left to right?",
      "Три карты — красная, синяя и зелёная — лежат в ряд рубашкой вверх в некотором порядке. Подсказка 1: красная карта не крайняя слева. Подсказка 2: синяя карта находится сразу справа от зелёной. Каков порядок слева направо?",
    ),
    options: [
      { id: "A", text: P("Green, Blue, Red", "Зелёная, синяя, красная") },
      { id: "B", text: P("Red, Green, Blue", "Красная, зелёная, синяя") },
      { id: "C", text: P("Blue, Green, Red", "Синяя, зелёная, красная") },
      { id: "D", text: P("Green, Red, Blue", "Зелёная, красная, синяя") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Blue must be immediately right of green, so they occupy adjacent positions in that order. If red were leftmost (red, green, blue), that would violate clue 1. So green and blue must occupy positions 1-2, leaving red in position 3: Green, Blue, Red.",
      "Синяя должна быть сразу справа от зелёной, то есть они стоят рядом в этом порядке. Если красная была бы крайней слева (красная, зелёная, синяя), это нарушило бы подсказку 1. Значит зелёная и синяя занимают позиции 1-2, а красная — позицию 3: зелёная, синяя, красная.",
    ),
    weight: 1.5,
  },
  {
    id: 527,
    category: "logical",
    difficulty: "hard",
    prompt: P(
      "Exactly one of three suspects — X, Y, Z — is guilty. X says: 'I am not guilty.' Y says: 'I am not guilty.' Z says: 'X is guilty.' Exactly one of these three statements is true. Who is guilty?",
      "Ровно один из трёх подозреваемых — X, Y, Z — виновен. X говорит: «Я не виновен». Y говорит: «Я не виновен». Z говорит: «X виновен». Ровно одно из этих трёх утверждений верно. Кто виновен?",
    ),
    options: [
      { id: "A", text: P("X", "X") },
      { id: "B", text: P("Y", "Y") },
      { id: "C", text: P("Z", "Z") },
      { id: "D", text: P("Cannot be determined", "Невозможно определить") },
    ],
    correctAnswer: "B",
    explanation: P(
      "If X were guilty: X's statement is false, Y's statement is true, Z's statement is true — 2 true statements, contradiction. If Z were guilty: X's statement is true, Y's statement is true, Z's statement is false — 2 true statements, contradiction. If Y is guilty: X's statement is true (X is innocent), Y's statement is false, Z's statement is false (X is not guilty) — exactly 1 true statement. Y is guilty.",
      "Если бы виновен был X: утверждение X ложно, утверждение Y истинно, утверждение Z истинно — 2 истинных, противоречие. Если бы виновен был Z: утверждение X истинно, утверждение Y истинно, утверждение Z ложно — 2 истинных, противоречие. Если виновен Y: утверждение X истинно (X невиновен), утверждение Y ложно, утверждение Z ложно (X не виновен) — ровно 1 истинное. Виновен Y.",
    ),
    weight: 2,
  },
  {
    id: 528,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "A bag contains only red and blue marbles, drawn one at a time and replaced each time. The last four draws were all blue. Is the next draw guaranteed to be red?",
      "В мешке только красные и синие шарики, их вытягивают по одному и каждый раз возвращают обратно. Последние четыре вытянутых шарика были синими. Гарантированно ли, что следующий шарик будет красным?",
    ),
    options: [
      { id: "A", text: P("No, each draw is independent of past draws.", "Нет, каждое вытягивание не зависит от предыдущих.") },
      { id: "B", text: P("Yes, red is now guaranteed.", "Да, теперь красный гарантирован.") },
      { id: "C", text: P("Yes, because the bag balances itself.", "Да, потому что мешок сам себя уравновешивает.") },
      { id: "D", text: P("No more blue marbles remain.", "Синих шариков больше не осталось.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since marbles are replaced after each draw, the outcome of past draws has no effect on future ones — assuming red is guaranteed after a run of blues is the gambler's fallacy.",
      "Так как шарики возвращаются в мешок после каждого вытягивания, результаты прошлых вытягиваний не влияют на будущие — предположение, что после серии синих гарантирован красный, является ошибкой игрока.",
    ),
    weight: 1.5,
  },
  {
    id: 529,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "In a race with four runners, Runner 1 finished before Runner 2. Runner 3 finished after Runner 4 but before Runner 1. What is the finishing order from fastest to slowest?",
      "В забеге с четырьмя бегунами Бегун 1 финишировал раньше Бегуна 2. Бегун 3 финишировал позже Бегуна 4, но раньше Бегуна 1. Каков порядок финиша от самого быстрого к самому медленному?",
    ),
    options: [
      { id: "A", text: P("Runner 4, Runner 3, Runner 1, Runner 2", "Бегун 4, Бегун 3, Бегун 1, Бегун 2") },
      { id: "B", text: P("Runner 1, Runner 3, Runner 4, Runner 2", "Бегун 1, Бегун 3, Бегун 4, Бегун 2") },
      { id: "C", text: P("Runner 3, Runner 4, Runner 1, Runner 2", "Бегун 3, Бегун 4, Бегун 1, Бегун 2") },
      { id: "D", text: P("Runner 4, Runner 1, Runner 3, Runner 2", "Бегун 4, Бегун 1, Бегун 3, Бегун 2") },
    ],
    correctAnswer: "A",
    explanation: P(
      "From the clues: Runner 4 finished before Runner 3, Runner 3 finished before Runner 1, and Runner 1 finished before Runner 2. Combined chain: 4, 3, 1, 2.",
      "Из подсказок: Бегун 4 финишировал раньше Бегуна 3, Бегун 3 — раньше Бегуна 1, а Бегун 1 — раньше Бегуна 2. Объединённая цепочка: 4, 3, 1, 2.",
    ),
    weight: 1.5,
  },
  {
    id: 530,
    category: "logical",
    difficulty: "easy",
    prompt: P(
      "Every whole number is either even or odd, never both. N is not odd. What can you conclude about N?",
      "Каждое целое число — либо чётное, либо нечётное, и не то и другое одновременно. N не является нечётным. Что можно сказать о N?",
    ),
    options: [
      { id: "A", text: P("N is even.", "N — чётное число.") },
      { id: "B", text: P("N is odd.", "N — нечётное число.") },
      { id: "C", text: P("N could be either.", "N может быть любым из них.") },
      { id: "D", text: P("N is not a whole number.", "N не является целым числом.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since every whole number is exactly one of even or odd, and N is not odd, N must be even.",
      "Так как каждое целое число является ровно одним из двух — чётным или нечётным, а N не нечётное, значит N чётное.",
    ),
    weight: 1,
  },
  {
    id: 531,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "Every working watch has moving hands. This object has no moving hands. Can it be a working watch?",
      "У каждых исправных часов есть движущиеся стрелки. У этого предмета нет движущихся стрелок. Может ли это быть исправными часами?",
    ),
    options: [
      { id: "A", text: P("No, it cannot be a working watch.", "Нет, это не могут быть исправные часы.") },
      { id: "B", text: P("Yes, it could still be a working watch.", "Да, это всё же могут быть исправные часы.") },
      { id: "C", text: P("Yes, it is definitely a working watch.", "Да, это точно исправные часы.") },
      { id: "D", text: P("It must be a clock, not a watch.", "Это должны быть настенные часы, а не наручные.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since every working watch has moving hands, anything without moving hands cannot be a working watch (contrapositive).",
      "Так как у каждых исправных часов есть движущиеся стрелки, всё, у чего их нет, не может быть исправными часами (метод от противного).",
    ),
    weight: 1.5,
  },
  {
    id: 532,
    category: "logical",
    difficulty: "hard",
    prompt: P(
      "On an island, knights always tell the truth and knaves always lie. You meet two inhabitants, A and B. A says: 'At least one of us is a knave.' What are A and B?",
      "На острове рыцари всегда говорят правду, а лжецы всегда лгут. Вы встречаете двух жителей, А и Б. А говорит: «Хотя бы один из нас — лжец». Кто такие А и Б?",
    ),
    options: [
      { id: "A", text: P("A is a knight, B is a knave.", "А — рыцарь, Б — лжец.") },
      { id: "B", text: P("A is a knave, B is a knight.", "А — лжец, Б — рыцарь.") },
      { id: "C", text: P("Both are knights.", "Оба — рыцари.") },
      { id: "D", text: P("Both are knaves.", "Оба — лжецы.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "If A were a knave, A's statement would be false, meaning neither is a knave — but that contradicts A being a knave. So A must be a knight, and the true statement 'at least one of us is a knave' means B is the knave.",
      "Если бы А был лжецом, его утверждение было бы ложным, то есть ни один из них не лжец — но это противоречит тому, что А лжец. Значит А — рыцарь, и его истинное утверждение «хотя бы один из нас лжец» означает, что Б — лжец.",
    ),
    weight: 2,
  },
  {
    id: 533,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "If it's sunny, we go to the beach. If we go to the beach, we bring sunscreen. We did not bring sunscreen. What must be true?",
      "Если солнечно, мы идём на пляж. Если мы идём на пляж, мы берём солнцезащитный крем. Мы не взяли крем. Что должно быть верно?",
    ),
    options: [
      { id: "A", text: P("It was not sunny.", "Не было солнечно.") },
      { id: "B", text: P("It was sunny.", "Было солнечно.") },
      { id: "C", text: P("We went to the beach.", "Мы пошли на пляж.") },
      { id: "D", text: P("Nothing can be concluded.", "Нельзя сделать никакого вывода.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "No sunscreen means we did not go to the beach (modus tollens on the second rule); not going to the beach means it was not sunny (modus tollens on the first rule).",
      "Нет крема — значит мы не пошли на пляж (modus tollens по второму правилу); не пошли на пляж — значит не было солнечно (modus tollens по первому правилу).",
    ),
    weight: 1.5,
  },
  {
    id: 534,
    category: "logical",
    difficulty: "hard",
    prompt: P(
      "Five sprinters — Nora, Omar, Priya, Quinn, and Rex — finish a race with no ties. Quinn beats Nora. Nora beats Omar. Omar beats exactly two people. Priya finishes last. Who finishes second?",
      "Пять спринтеров — Нора, Омар, Прия, Куинн и Рекс — финишируют без равных результатов. Куинн опережает Нору. Нора опережает Омара. Омар опережает ровно двух человек. Прия финиширует последней. Кто финиширует вторым?",
    ),
    options: [
      { id: "A", text: P("Omar", "Омар") },
      { id: "B", text: P("Nora", "Нора") },
      { id: "C", text: P("Rex", "Рекс") },
      { id: "D", text: P("Quinn", "Куинн") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Omar beats exactly two people, so exactly two finish behind him — Omar is 3rd of 5. Since Quinn beats Nora beats Omar, both Quinn and Nora must be ahead of Omar (positions 1-2), and Quinn beats Nora, so Quinn is 1st and Nora is 2nd. Priya is 5th, leaving Rex in 4th.",
      "Омар опережает ровно двух человек, значит ровно двое финишируют позади него — Омар на 3-м месте из 5. Так как Куинн опережает Нору, а та — Омара, оба Куинн и Нора должны быть впереди Омара (места 1-2), а Куинн опережает Нору, значит Куинн 1-й, а Нора 2-я. Прия 5-я, значит Рекс — 4-й.",
    ),
    weight: 2,
  },
  {
    id: 535,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "Two whole numbers are multiplied together and the result is odd. What must be true about both numbers?",
      "Два целых числа умножили друг на друга, и результат оказался нечётным. Что должно быть верно про оба числа?",
    ),
    options: [
      { id: "A", text: P("Both numbers must be odd.", "Оба числа должны быть нечётными.") },
      { id: "B", text: P("Both numbers must be even.", "Оба числа должны быть чётными.") },
      { id: "C", text: P("Exactly one must be even.", "Ровно одно из них должно быть чётным.") },
      { id: "D", text: P("At least one must be even.", "Хотя бы одно из них должно быть чётным.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "If either number were even, the product would be even. Since the product is odd, neither number can be even — both must be odd.",
      "Если бы хотя бы одно число было чётным, произведение было бы чётным. Так как произведение нечётное, ни одно из чисел не может быть чётным — оба должны быть нечётными.",
    ),
    weight: 1.5,
  },
  {
    id: 536,
    category: "logical",
    difficulty: "easy",
    prompt: P(
      "A number is divisible by 6. What must be true about its divisibility by 2 and by 3?",
      "Число делится на 6. Что должно быть верно относительно его делимости на 2 и на 3?",
    ),
    options: [
      { id: "A", text: P("It is divisible by both 2 and 3.", "Оно делится и на 2, и на 3.") },
      { id: "B", text: P("It is divisible by 2 but not 3.", "Оно делится на 2, но не на 3.") },
      { id: "C", text: P("It is divisible by 3 but not 2.", "Оно делится на 3, но не на 2.") },
      { id: "D", text: P("It is divisible by neither.", "Оно не делится ни на то, ни на другое.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since 6 = 2 × 3, any number divisible by 6 must also be divisible by both of its factors, 2 and 3.",
      "Так как 6 = 2 × 3, любое число, делящееся на 6, обязательно делится и на оба его множителя — 2 и 3.",
    ),
    weight: 1,
  },
  {
    id: 537,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "All juveniles need parental consent to enroll in the program. Ben enrolled without parental consent. What can we conclude about Ben?",
      "Все несовершеннолетние должны получить согласие родителей для участия в программе. Бен зарегистрировался без согласия родителей. Что можно сказать о Бене?",
    ),
    options: [
      { id: "A", text: P("Ben is not a juvenile.", "Бен не является несовершеннолетним.") },
      { id: "B", text: P("Ben is a juvenile.", "Бен несовершеннолетний.") },
      { id: "C", text: P("Ben's enrollment is invalid.", "Регистрация Бена недействительна.") },
      { id: "D", text: P("Nothing can be concluded.", "Нельзя сделать никакого вывода.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Since all juveniles require parental consent to enroll, and Ben enrolled without it, Ben cannot be a juvenile (contrapositive).",
      "Так как все несовершеннолетние должны получить согласие родителей, а Бен зарегистрировался без него, он не может быть несовершеннолетним (метод от противного).",
    ),
    weight: 1.5,
  },
  {
    id: 538,
    category: "logical",
    difficulty: "hard",
    prompt: P(
      "In a family, the father's rule is: 'No dessert unless the vegetables are finished.' Mia had dessert tonight. What must be true?",
      "В семье действует правило отца: «Десерт только если овощи съедены». Сегодня Мия получила десерт. Что должно быть верно?",
    ),
    options: [
      { id: "A", text: P("Mia finished her vegetables.", "Мия съела свои овощи.") },
      { id: "B", text: P("Mia did not finish her vegetables.", "Мия не съела свои овощи.") },
      { id: "C", text: P("Mia skipped dinner.", "Мия пропустила ужин.") },
      { id: "D", text: P("Nothing can be concluded.", "Нельзя сделать никакого вывода.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "Finishing vegetables is a necessary condition for dessert. Since Mia had dessert, the necessary condition must have been met: she finished her vegetables.",
      "Съеденные овощи — необходимое условие для десерта. Так как Мия получила десерт, необходимое условие должно быть выполнено: она съела овощи.",
    ),
    weight: 2,
  },
  {
    id: 539,
    category: "logical",
    difficulty: "medium",
    prompt: P(
      "'If today is a holiday, the office is closed.' The office is closed today. Can we conclude today is a holiday?",
      "«Если сегодня праздник, офис закрыт». Сегодня офис закрыт. Можно ли заключить, что сегодня праздник?",
    ),
    options: [
      { id: "A", text: P("No, this does not follow — the office could be closed for another reason.", "Нет, это не следует обязательно — офис может быть закрыт по другой причине.") },
      { id: "B", text: P("Yes, it must be a holiday.", "Да, это обязательно праздник.") },
      { id: "C", text: P("Yes, but only if it's also a weekend.", "Да, но только если это ещё и выходной.") },
      { id: "D", text: P("No, the office is never closed on holidays.", "Нет, офис никогда не закрывается на праздники.") },
    ],
    correctAnswer: "A",
    explanation: P(
      "This is the fallacy of affirming the consequent: the rule only guarantees closure on holidays, not that closure implies a holiday — the office could be closed for other reasons (e.g. maintenance).",
      "Это ошибка утверждения следствия: правило гарантирует закрытие только в праздники, но не то, что закрытие означает праздник — офис может быть закрыт по другим причинам (например, на ремонт).",
    ),
    weight: 1.5,
  },
];
