import type { Question } from "../types";

const P = (en: string, ru: string) => ({ en, ru });
const SERIES_PROMPT = (series: string) => ({
  en: `What is the next number in the series?\n\n${series}`,
  ru: `Какое число продолжает ряд?\n\n${series}`,
});

export const numericalQuestions: Question[] = [
  {
    id: 201,
    category: "numerical",
    difficulty: "easy",
    prompt: SERIES_PROMPT("3, 6, 9, 12, 15, __"),
    options: [
      { id: "A", text: P("16", "16") },
      { id: "B", text: P("17", "17") },
      { id: "C", text: P("18", "18") },
      { id: "D", text: P("21", "21") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Each number increases by 3. 15 + 3 = 18.",
      "Каждое число увеличивается на 3. 15 + 3 = 18.",
    ),
    weight: 1,
  },
  {
    id: 202,
    category: "numerical",
    difficulty: "easy",
    prompt: SERIES_PROMPT("5, 10, 15, 20, 25, __"),
    options: [
      { id: "A", text: P("28", "28") },
      { id: "B", text: P("30", "30") },
      { id: "C", text: P("32", "32") },
      { id: "D", text: P("35", "35") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Each number increases by 5. 25 + 5 = 30.",
      "Каждое число увеличивается на 5. 25 + 5 = 30.",
    ),
    weight: 1,
  },
  {
    id: 203,
    category: "numerical",
    difficulty: "easy",
    prompt: SERIES_PROMPT("1, 2, 4, 8, 16, __"),
    options: [
      { id: "A", text: P("18", "18") },
      { id: "B", text: P("24", "24") },
      { id: "C", text: P("30", "30") },
      { id: "D", text: P("32", "32") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Each number is doubled. 16 × 2 = 32.",
      "Каждое число удваивается. 16 × 2 = 32.",
    ),
    weight: 1,
  },
  {
    id: 204,
    category: "numerical",
    difficulty: "easy",
    prompt: SERIES_PROMPT("20, 18, 16, 14, 12, __"),
    options: [
      { id: "A", text: P("9", "9") },
      { id: "B", text: P("10", "10") },
      { id: "C", text: P("11", "11") },
      { id: "D", text: P("8", "8") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Each number decreases by 2. 12 − 2 = 10.",
      "Каждое число уменьшается на 2. 12 − 2 = 10.",
    ),
    weight: 1,
  },
  {
    id: 205,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("2, 6, 18, 54, 162, __"),
    options: [
      { id: "A", text: P("324", "324") },
      { id: "B", text: P("378", "378") },
      { id: "C", text: P("486", "486") },
      { id: "D", text: P("648", "648") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Each number is multiplied by 3. 162 × 3 = 486.",
      "Каждое число умножается на 3. 162 × 3 = 486.",
    ),
    weight: 1.5,
  },
  {
    id: 206,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("1, 4, 9, 16, 25, 36, __"),
    options: [
      { id: "A", text: P("42", "42") },
      { id: "B", text: P("45", "45") },
      { id: "C", text: P("48", "48") },
      { id: "D", text: P("49", "49") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Each number is a perfect square: 1², 2², 3² ... 7² = 49.",
      "Каждое число — точный квадрат: 1², 2², 3² ... 7² = 49.",
    ),
    weight: 1.5,
  },
  {
    id: 207,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("100, 90, 81, 73, 66, __"),
    options: [
      { id: "A", text: P("58", "58") },
      { id: "B", text: P("59", "59") },
      { id: "C", text: P("60", "60") },
      { id: "D", text: P("61", "61") },
    ],
    correctAnswer: "C",
    explanation: P(
      "The differences shrink by 1 each step: −10, −9, −8, −7, −6. 66 − 6 = 60.",
      "Разница уменьшается на 1 каждый раз: −10, −9, −8, −7, −6. 66 − 6 = 60.",
    ),
    weight: 1.5,
  },
  {
    id: 208,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("4, 7, 11, 16, 22, __"),
    options: [
      { id: "A", text: P("27", "27") },
      { id: "B", text: P("28", "28") },
      { id: "C", text: P("29", "29") },
      { id: "D", text: P("30", "30") },
    ],
    correctAnswer: "C",
    explanation: P(
      "The differences increase by 1 each time: +3, +4, +5, +6, +7. 22 + 7 = 29.",
      "Разница увеличивается на 1 каждый раз: +3, +4, +5, +6, +7. 22 + 7 = 29.",
    ),
    weight: 1.5,
  },
  {
    id: 209,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("2, 4, 8, 14, 22, __"),
    options: [
      { id: "A", text: P("30", "30") },
      { id: "B", text: P("32", "32") },
      { id: "C", text: P("34", "34") },
      { id: "D", text: P("36", "36") },
    ],
    correctAnswer: "B",
    explanation: P(
      "The differences increase by 2 each time: +2, +4, +6, +8, +10. 22 + 10 = 32.",
      "Разница увеличивается на 2 каждый раз: +2, +4, +6, +8, +10. 22 + 10 = 32.",
    ),
    weight: 1.5,
  },
  {
    id: 210,
    category: "numerical",
    difficulty: "hard",
    prompt: SERIES_PROMPT("1, 1, 2, 3, 5, 8, 13, __"),
    options: [
      { id: "A", text: P("18", "18") },
      { id: "B", text: P("19", "19") },
      { id: "C", text: P("20", "20") },
      { id: "D", text: P("21", "21") },
    ],
    correctAnswer: "D",
    explanation: P(
      "This is the Fibonacci sequence: each number is the sum of the two before it. 8 + 13 = 21.",
      "Это последовательность Фибоначчи: каждое число — сумма двух предыдущих. 8 + 13 = 21.",
    ),
    weight: 2,
  },
  {
    id: 211,
    category: "numerical",
    difficulty: "hard",
    prompt: SERIES_PROMPT("2, 3, 5, 9, 17, __"),
    options: [
      { id: "A", text: P("29", "29") },
      { id: "B", text: P("31", "31") },
      { id: "C", text: P("33", "33") },
      { id: "D", text: P("35", "35") },
    ],
    correctAnswer: "C",
    explanation: P(
      "The differences double each time: +1, +2, +4, +8, so the next difference is +16. 17 + 16 = 33.",
      "Разница удваивается каждый раз: +1, +2, +4, +8, значит следующая разница +16. 17 + 16 = 33.",
    ),
    weight: 2,
  },
  {
    id: 212,
    category: "numerical",
    difficulty: "hard",
    prompt: SERIES_PROMPT("1, 2, 6, 24, 120, __"),
    options: [
      { id: "A", text: P("240", "240") },
      { id: "B", text: P("480", "480") },
      { id: "C", text: P("600", "600") },
      { id: "D", text: P("720", "720") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Each term is multiplied by an increasing factor: ×2, ×3, ×4, ×5, then ×6. 120 × 6 = 720.",
      "Каждый член умножается на возрастающий множитель: ×2, ×3, ×4, ×5, затем ×6. 120 × 6 = 720.",
    ),
    weight: 2,
  },
  {
    id: 213,
    category: "numerical",
    difficulty: "hard",
    prompt: SERIES_PROMPT("7, 11, 18, 29, 47, __"),
    options: [
      { id: "A", text: P("66", "66") },
      { id: "B", text: P("71", "71") },
      { id: "C", text: P("76", "76") },
      { id: "D", text: P("82", "82") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Each number is the sum of the two preceding numbers (like Fibonacci): 29 + 47 = 76.",
      "Каждое число — сумма двух предыдущих (как в ряду Фибоначчи): 29 + 47 = 76.",
    ),
    weight: 2,
  },
  {
    id: 214,
    category: "numerical",
    difficulty: "hard",
    prompt: SERIES_PROMPT("3, 4, 7, 11, 18, 29, __"),
    options: [
      { id: "A", text: P("40", "40") },
      { id: "B", text: P("42", "42") },
      { id: "C", text: P("45", "45") },
      { id: "D", text: P("47", "47") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Each number is the sum of the two preceding numbers: 18 + 29 = 47.",
      "Каждое число — сумма двух предыдущих: 18 + 29 = 47.",
    ),
    weight: 2,
  },
  {
    id: 215,
    category: "numerical",
    difficulty: "easy",
    prompt: SERIES_PROMPT("8, 15, 22, 29, 36, __"),
    options: [
      { id: "A", text: P("41", "41") },
      { id: "B", text: P("42", "42") },
      { id: "C", text: P("43", "43") },
      { id: "D", text: P("45", "45") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Each number increases by 7. 36 + 7 = 43.",
      "Каждое число увеличивается на 7. 36 + 7 = 43.",
    ),
    weight: 1,
  },
  {
    id: 216,
    category: "numerical",
    difficulty: "easy",
    prompt: SERIES_PROMPT("90, 81, 72, 63, 54, __"),
    options: [
      { id: "A", text: P("42", "42") },
      { id: "B", text: P("44", "44") },
      { id: "C", text: P("45", "45") },
      { id: "D", text: P("46", "46") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Each number decreases by 9. 54 − 9 = 45.",
      "Каждое число уменьшается на 9. 54 − 9 = 45.",
    ),
    weight: 1,
  },
  {
    id: 217,
    category: "numerical",
    difficulty: "easy",
    prompt: SERIES_PROMPT("3, 5, 9, 11, 15, __"),
    options: [
      { id: "A", text: P("17", "17") },
      { id: "B", text: P("18", "18") },
      { id: "C", text: P("19", "19") },
      { id: "D", text: P("21", "21") },
    ],
    correctAnswer: "A",
    explanation: P(
      "The additions alternate +2, +4: 3+2=5, 5+4=9, 9+2=11, 11+4=15, 15+2=17.",
      "Приращения чередуются +2, +4: 3+2=5, 5+4=9, 9+2=11, 11+4=15, 15+2=17.",
    ),
    weight: 1,
  },
  {
    id: 218,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("4, 8, 5, 10, 7, 14, __"),
    options: [
      { id: "A", text: P("9", "9") },
      { id: "B", text: P("10", "10") },
      { id: "C", text: P("11", "11") },
      { id: "D", text: P("12", "12") },
    ],
    correctAnswer: "C",
    explanation: P(
      "The rule alternates ×2 then −3: 4×2=8, 8−3=5, 5×2=10, 10−3=7, 7×2=14, 14−3=11.",
      "Правило чередуется: ×2, затем −3: 4×2=8, 8−3=5, 5×2=10, 10−3=7, 7×2=14, 14−3=11.",
    ),
    weight: 1.5,
  },
  {
    id: 219,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("2, 5, 10, 17, 26, __"),
    options: [
      { id: "A", text: P("35", "35") },
      { id: "B", text: P("36", "36") },
      { id: "C", text: P("37", "37") },
      { id: "D", text: P("39", "39") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Each term equals n² + 1: 1²+1=2, 2²+1=5, 3²+1=10, 4²+1=17, 5²+1=26, 6²+1=37.",
      "Каждый член равен n² + 1: 1²+1=2, 2²+1=5, 3²+1=10, 4²+1=17, 5²+1=26, 6²+1=37.",
    ),
    weight: 1.5,
  },
  {
    id: 220,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("1, 8, 27, 64, 125, __"),
    options: [
      { id: "A", text: P("196", "196") },
      { id: "B", text: P("206", "206") },
      { id: "C", text: P("216", "216") },
      { id: "D", text: P("226", "226") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Each number is a perfect cube: 1³, 2³, 3³, 4³, 5³, then 6³ = 216.",
      "Каждое число — точный куб: 1³, 2³, 3³, 4³, 5³, затем 6³ = 216.",
    ),
    weight: 1.5,
  },
  {
    id: 221,
    category: "numerical",
    difficulty: "hard",
    prompt: SERIES_PROMPT("3, 5, 8, 13, 21, 34, __"),
    options: [
      { id: "A", text: P("52", "52") },
      { id: "B", text: P("55", "55") },
      { id: "C", text: P("58", "58") },
      { id: "D", text: P("60", "60") },
    ],
    correctAnswer: "B",
    explanation: P(
      "This is a Fibonacci-style sequence starting from 3 and 5: each term is the sum of the two before it. 21 + 34 = 55.",
      "Это ряд типа Фибоначчи, начинающийся с 3 и 5: каждый член — сумма двух предыдущих. 21 + 34 = 55.",
    ),
    weight: 2,
  },
  {
    id: 222,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("2, 3, 5, 7, 11, 13, __"),
    options: [
      { id: "A", text: P("15", "15") },
      { id: "B", text: P("16", "16") },
      { id: "C", text: P("17", "17") },
      { id: "D", text: P("19", "19") },
    ],
    correctAnswer: "C",
    explanation: P(
      "This is the sequence of prime numbers in order. The next prime after 13 is 17.",
      "Это последовательность простых чисел по порядку. Следующее простое число после 13 — это 17.",
    ),
    weight: 1.5,
  },
  {
    id: 223,
    category: "numerical",
    difficulty: "easy",
    prompt: P(
      "A shirt costs $80. After a 25% discount, what is the sale price?",
      "Рубашка стоит 80 долларов. Какова цена после скидки 25%?",
    ),
    options: [
      { id: "A", text: P("$55", "55 $") },
      { id: "B", text: P("$58", "58 $") },
      { id: "C", text: P("$60", "60 $") },
      { id: "D", text: P("$65", "65 $") },
    ],
    correctAnswer: "C",
    explanation: P(
      "25% of $80 is $20. $80 − $20 = $60.",
      "25% от 80 $ составляет 20 $. 80 $ − 20 $ = 60 $.",
    ),
    weight: 1,
  },
  {
    id: 224,
    category: "numerical",
    difficulty: "medium",
    prompt: P(
      "The ratio of apples to oranges in a basket is 3:5. If there are 24 fruits total, how many are apples?",
      "Соотношение яблок и апельсинов в корзине — 3:5. Если всего 24 фрукта, сколько из них яблок?",
    ),
    options: [
      { id: "A", text: P("8", "8") },
      { id: "B", text: P("9", "9") },
      { id: "C", text: P("10", "10") },
      { id: "D", text: P("15", "15") },
    ],
    correctAnswer: "B",
    explanation: P(
      "The ratio parts sum to 3+5=8. Each part equals 24÷8=3 fruits. Apples: 3 parts × 3 = 9.",
      "Сумма частей отношения: 3+5=8. Каждая часть равна 24÷8=3 фрукта. Яблоки: 3 части × 3 = 9.",
    ),
    weight: 1.5,
  },
  {
    id: 225,
    category: "numerical",
    difficulty: "medium",
    prompt: P(
      "The average of four numbers is 15. Three of them are 10, 12, and 18. What is the fourth number?",
      "Среднее арифметическое четырёх чисел равно 15. Три из них — 10, 12 и 18. Каково четвёртое число?",
    ),
    options: [
      { id: "A", text: P("18", "18") },
      { id: "B", text: P("20", "20") },
      { id: "C", text: P("22", "22") },
      { id: "D", text: P("24", "24") },
    ],
    correctAnswer: "B",
    explanation: P(
      "The total of four numbers must be 15 × 4 = 60. The three known numbers sum to 40, so the fourth is 60 − 40 = 20.",
      "Сумма четырёх чисел должна быть 15 × 4 = 60. Три известных числа в сумме дают 40, значит четвёртое равно 60 − 40 = 20.",
    ),
    weight: 1.5,
  },
  {
    id: 226,
    category: "numerical",
    difficulty: "hard",
    prompt: P(
      "Worker A can finish a job alone in 6 days. Worker B can finish the same job alone in 3 days. Working together, how many days will it take?",
      "Работник А может выполнить работу самостоятельно за 6 дней. Работник Б — за 3 дня. За сколько дней они выполнят работу вместе?",
    ),
    options: [
      { id: "A", text: P("1", "1") },
      { id: "B", text: P("2", "2") },
      { id: "C", text: P("3", "3") },
      { id: "D", text: P("4", "4") },
    ],
    correctAnswer: "B",
    explanation: P(
      "A's rate is 1/6 job per day, B's rate is 1/3 job per day. Combined rate: 1/6 + 1/3 = 1/2 job per day, so the job takes 2 days.",
      "Скорость А — 1/6 работы в день, скорость Б — 1/3 работы в день. Суммарная скорость: 1/6 + 1/3 = 1/2 работы в день, значит работа займёт 2 дня.",
    ),
    weight: 2,
  },
  {
    id: 227,
    category: "numerical",
    difficulty: "easy",
    prompt: P(
      "A car travels 240 km in 4 hours at a constant speed. At the same speed, how far will it travel in 7 hours?",
      "Автомобиль проезжает 240 км за 4 часа с постоянной скоростью. Сколько он проедет за 7 часов с той же скоростью?",
    ),
    options: [
      { id: "A", text: P("380 km", "380 км") },
      { id: "B", text: P("400 km", "400 км") },
      { id: "C", text: P("420 km", "420 км") },
      { id: "D", text: P("440 km", "440 км") },
    ],
    correctAnswer: "C",
    explanation: P(
      "The speed is 240 ÷ 4 = 60 km/h. In 7 hours: 60 × 7 = 420 km.",
      "Скорость составляет 240 ÷ 4 = 60 км/ч. За 7 часов: 60 × 7 = 420 км.",
    ),
    weight: 1,
  },
  {
    id: 228,
    category: "numerical",
    difficulty: "hard",
    prompt: P(
      "Tom is currently 3 times as old as his son. In 12 years, Tom will be exactly twice as old as his son. How old is Tom now?",
      "Сейчас Том втрое старше своего сына. Через 12 лет Том будет ровно в два раза старше сына. Сколько лет Тому сейчас?",
    ),
    options: [
      { id: "A", text: P("30", "30") },
      { id: "B", text: P("33", "33") },
      { id: "C", text: P("36", "36") },
      { id: "D", text: P("39", "39") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Let the son's age be x, so Tom is 3x. In 12 years: 3x + 12 = 2(x + 12), which gives x = 12. Tom is now 3 × 12 = 36.",
      "Пусть возраст сына — x, тогда Том — 3x. Через 12 лет: 3x + 12 = 2(x + 12), отсюда x = 12. Тому сейчас 3 × 12 = 36.",
    ),
    weight: 2,
  },
  {
    id: 229,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("3, 7, 15, 31, 63, __"),
    options: [
      { id: "A", text: P("119", "119") },
      { id: "B", text: P("123", "123") },
      { id: "C", text: P("127", "127") },
      { id: "D", text: P("131", "131") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Each number doubles and adds 1: 3×2+1=7, 7×2+1=15, 15×2+1=31, 31×2+1=63, 63×2+1=127.",
      "Каждое число удваивается и увеличивается на 1: 3×2+1=7, 7×2+1=15, 15×2+1=31, 31×2+1=63, 63×2+1=127.",
    ),
    weight: 1.5,
  },
  {
    id: 230,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("800, 400, 200, 100, __"),
    options: [
      { id: "A", text: P("40", "40") },
      { id: "B", text: P("45", "45") },
      { id: "C", text: P("50", "50") },
      { id: "D", text: P("55", "55") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Each number is half of the one before it. 100 ÷ 2 = 50.",
      "Каждое число — половина предыдущего. 100 ÷ 2 = 50.",
    ),
    weight: 1.5,
  },
  {
    id: 231,
    category: "numerical",
    difficulty: "hard",
    prompt: SERIES_PROMPT("2, 5, 11, 23, 47, __"),
    options: [
      { id: "A", text: P("90", "90") },
      { id: "B", text: P("92", "92") },
      { id: "C", text: P("94", "94") },
      { id: "D", text: P("95", "95") },
    ],
    correctAnswer: "D",
    explanation: P(
      "Each number doubles and adds 1: 2×2+1=5, 5×2+1=11, 11×2+1=23, 23×2+1=47, 47×2+1=95.",
      "Каждое число удваивается и увеличивается на 1: 2×2+1=5, 5×2+1=11, 11×2+1=23, 23×2+1=47, 47×2+1=95.",
    ),
    weight: 2,
  },
  {
    id: 232,
    category: "numerical",
    difficulty: "medium",
    prompt: P(
      "A town's population is 200 and grows by 10% each year. What will the population be after 2 years (rounded to the nearest whole number)?",
      "Население города составляет 200 человек и растёт на 10% в год. Каким будет население через 2 года (округлённо)?",
    ),
    options: [
      { id: "A", text: P("220", "220") },
      { id: "B", text: P("230", "230") },
      { id: "C", text: P("240", "240") },
      { id: "D", text: P("242", "242") },
    ],
    correctAnswer: "D",
    explanation: P(
      "After year 1: 200 × 1.1 = 220. After year 2: 220 × 1.1 = 242.",
      "После 1-го года: 200 × 1,1 = 220. После 2-го года: 220 × 1,1 = 242.",
    ),
    weight: 1.5,
  },
  {
    id: 233,
    category: "numerical",
    difficulty: "easy",
    prompt: SERIES_PROMPT("1, 3, 6, 10, 15, __"),
    options: [
      { id: "A", text: P("18", "18") },
      { id: "B", text: P("20", "20") },
      { id: "C", text: P("21", "21") },
      { id: "D", text: P("25", "25") },
    ],
    correctAnswer: "C",
    explanation: P(
      "These are triangular numbers, where each term adds one more than the previous addition: +2, +3, +4, +5, +6. 15 + 6 = 21.",
      "Это треугольные числа: каждая добавка на 1 больше предыдущей: +2, +3, +4, +5, +6. 15 + 6 = 21.",
    ),
    weight: 1,
  },
  {
    id: 234,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("5, 10, 8, 13, 11, 16, __"),
    options: [
      { id: "A", text: P("13", "13") },
      { id: "B", text: P("14", "14") },
      { id: "C", text: P("15", "15") },
      { id: "D", text: P("18", "18") },
    ],
    correctAnswer: "B",
    explanation: P(
      "The additions alternate +5, −2: 5+5=10, 10−2=8, 8+5=13, 13−2=11, 11+5=16, 16−2=14.",
      "Приращения чередуются +5, −2: 5+5=10, 10−2=8, 8+5=13, 13−2=11, 11+5=16, 16−2=14.",
    ),
    weight: 1.5,
  },
  {
    id: 235,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("0, 2, 6, 12, 20, __"),
    options: [
      { id: "A", text: P("28", "28") },
      { id: "B", text: P("30", "30") },
      { id: "C", text: P("32", "32") },
      { id: "D", text: P("36", "36") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Each term equals n² − n: 1²−1=0, 2²−2=2, 3²−3=6, 4²−4=12, 5²−5=20, 6²−6=30.",
      "Каждый член равен n² − n: 1²−1=0, 2²−2=2, 3²−3=6, 4²−4=12, 5²−5=20, 6²−6=30.",
    ),
    weight: 1.5,
  },
  {
    id: 236,
    category: "numerical",
    difficulty: "easy",
    prompt: P(
      "$1000 is invested at 5% simple interest per year. How much interest is earned after 3 years?",
      "1000 $ вложены под 5% простых процентов в год. Сколько процентов будет накоплено за 3 года?",
    ),
    options: [
      { id: "A", text: P("$100", "100 $") },
      { id: "B", text: P("$150", "150 $") },
      { id: "C", text: P("$200", "200 $") },
      { id: "D", text: P("$250", "250 $") },
    ],
    correctAnswer: "B",
    explanation: P(
      "Simple interest = Principal × Rate × Time = 1000 × 0.05 × 3 = $150.",
      "Простые проценты = Сумма × Ставка × Время = 1000 × 0,05 × 3 = 150 $.",
    ),
    weight: 1,
  },
  {
    id: 237,
    category: "numerical",
    difficulty: "medium",
    prompt: P(
      "5 workers can finish a job in 12 days, all working at the same steady rate. How many days would 10 workers need to finish the same job?",
      "5 рабочих выполняют работу за 12 дней, работая с одинаковой постоянной скоростью. За сколько дней 10 рабочих выполнят ту же работу?",
    ),
    options: [
      { id: "A", text: P("4", "4") },
      { id: "B", text: P("5", "5") },
      { id: "C", text: P("6", "6") },
      { id: "D", text: P("8", "8") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Total work = 5 workers × 12 days = 60 worker-days. With 10 workers: 60 ÷ 10 = 6 days.",
      "Общий объём работы = 5 рабочих × 12 дней = 60 человеко-дней. С 10 рабочими: 60 ÷ 10 = 6 дней.",
    ),
    weight: 1.5,
  },
  {
    id: 238,
    category: "numerical",
    difficulty: "hard",
    prompt: SERIES_PROMPT("2, 6, 5, 15, 14, 42, __"),
    options: [
      { id: "A", text: P("39", "39") },
      { id: "B", text: P("40", "40") },
      { id: "C", text: P("41", "41") },
      { id: "D", text: P("43", "43") },
    ],
    correctAnswer: "C",
    explanation: P(
      "The rule alternates ×3 then −1: 2×3=6, 6−1=5, 5×3=15, 15−1=14, 14×3=42, 42−1=41.",
      "Правило чередуется: ×3, затем −1: 2×3=6, 6−1=5, 5×3=15, 15−1=14, 14×3=42, 42−1=41.",
    ),
    weight: 2,
  },
  {
    id: 239,
    category: "numerical",
    difficulty: "hard",
    prompt: P(
      "A jacket originally costs $200. It is first discounted by 20%, then the new price is discounted by an additional 10%. What is the final price?",
      "Куртка стоит 200 $. Сначала на неё делают скидку 20%, а затем на новую цену делают ещё одну скидку 10%. Какова итоговая цена?",
    ),
    options: [
      { id: "A", text: P("$140", "140 $") },
      { id: "B", text: P("$142", "142 $") },
      { id: "C", text: P("$144", "144 $") },
      { id: "D", text: P("$150", "150 $") },
    ],
    correctAnswer: "C",
    explanation: P(
      "After the first discount: 200 × 0.8 = $160. After the second discount: 160 × 0.9 = $144.",
      "После первой скидки: 200 × 0,8 = 160 $. После второй скидки: 160 × 0,9 = 144 $.",
    ),
    weight: 2,
  },
  {
    id: 240,
    category: "numerical",
    difficulty: "medium",
    prompt: SERIES_PROMPT("2, 3, 4, 6, 9, 14, __"),
    options: [
      { id: "A", text: P("20", "20") },
      { id: "B", text: P("21", "21") },
      { id: "C", text: P("22", "22") },
      { id: "D", text: P("24", "24") },
    ],
    correctAnswer: "C",
    explanation: P(
      "Each term equals the sum of the two before it, minus 1: 3+2−1=4, 4+3−1=6, 6+4−1=9, 9+6−1=14, 14+9−1=22.",
      "Каждый член равен сумме двух предыдущих минус 1: 3+2−1=4, 4+3−1=6, 6+4−1=9, 9+6−1=14, 14+9−1=22.",
    ),
    weight: 1.5,
  },
];
